TESTSUITE/tbdef_wsc.f90
TESTSUITE/tests_peeq.f90
meson.build
xtb/eeq_model.f90
xtb/generate_wsc.f90
xtb/peeq_module.f90
xtb/tbdef_wsc.f90

- does not include molecule specific information anymore
- only topological information in WSC (setup only required once)
- now possible for arbitrary periodicities
- tests for 0D and 3D Wigner-Seitz cell setup

refactored the Wigner-Seitz cell representation

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

- bug report template
- feature request template

Add issue templates for this repo

---

meson.build
xtb/bias_path.f90
xtb/dynamic.f90
xtb/geoopt_driver.f90
xtb/hessian.f90
xtb/mdoptim.f90
xtb/modef.f90
xtb/optimizer.f90
xtb/program_main.f90
xtb/relaxation_engine.f90
xtb/scan_driver.f90
xtb/screening.f90
xtb/single.f90
xtb/tbdef_calculator.f90

- wraps basis set and parametrisation types

new tight-binding calculator type

---

man/man7/xcontrol.7.txt
xtb/constrain_param.f90

- new instruction changing the mass of all elements of a kind

allow changing mass of all elements of a kind via xcontrol

---

TESTSUITE/gfn0.f90
TESTSUITE/peeq.f90
meson.build

setup a reproducible environment for running the testsuite (ignore user `.xtbrc` and parameter files)

make sure the correct environment is setup in meson.build

---

TESTSUITE/geometry_reader.f90
TESTSUITE/tests_peeq.f90
meson.build
xtb/molecule_reader.f90
xtb/molecule_writer.f90
xtb/tbmod_file_utils.f90

New geometry input format: DFTB+ genFormat

---

python/README.md

- fix some typos in python/README.md

Update README for python package

---

TESTSUITE/thermo.f90
xtb/enso_printout.f90
xtb/main_property.f90
xtb/tbdef_data.f90

Adding ZPVE printout to the enso_printout

Adding ZPVE to enso_printout

---

meson.build
xtb/main_property.f90
xtb/scf_module.f90

better CM5 routines

---

xtb/argparser.f90
xtb/program_main.f90

Bugfix: enable GFN0 correctly from detailed input

---

xtb/optimizer.f90

Bugfix: ANC-opt hessian read-in error

---

xtb/tbmod_file_utils.f90

- works than also on `POSCAR` files.

Also try only basename to figure out filetype

---

TESTSUITE/c_api_example.c

add necessary file for C-API test

---

xtb/header.f90

Change disclaimer in printout to reflect LGPL3+

---

TESTSUITE/dftd4.f90
TESTSUITE/eeq_model.f90
TESTSUITE/gfn0.f90
TESTSUITE/gfn1.f90
TESTSUITE/gfn2.f90
TESTSUITE/peeq.f90
cmake/Files.cmake
meson.build
python/xtb/interface.py
xtb/calculator.f90
xtb/dftd3.f
xtb/dftd4.f90
xtb/dftd4_parameters.f90
xtb/dispplot.f90
xtb/eeq_model.f90
xtb/gfn0_calculator.f90
xtb/gfn1_calculator.f90
xtb/gfn2_calculator.f90
xtb/gfn_paramset.f90
xtb/iniq.f90
xtb/main_property.f90
xtb/peeq_module.f90
xtb/program_main.f90
xtb/qmdff.f90
xtb/scc_core.f90
xtb/scf_module.f90
xtb/surfac.f
xtb/tbdef_basisset.f90
xtb/typedef/dispersion_model.f90
xtb/xbasis.f90

better basisset representation and improved dispersion model setup.

refactoring of dispersion and basisset

---

TESTSUITE/dftd4.f90
TESTSUITE/eeq_model.f90
TESTSUITE/gfn0.f90
TESTSUITE/gfn1.f90
TESTSUITE/gfn2.f90
TESTSUITE/peeq.f90
cmake/Files.cmake
mctc/mctc_logging.f90
meson.build
xtb/c_api.f90
xtb/calculator.f90
xtb/eeq_model.f90
xtb/gfn0_calculator.f90
xtb/gfn1_calculator.f90
xtb/gfn2_calculator.f90
xtb/peeq_module.f90
xtb/scc_core.f90
xtb/scf_module.f90
xtb/single.f90
xtb/tbdef_options.f90

necessary for #102, related to #104

error handling mechanism using local variables

---

cmake/CMakeLists.txt
xtb/esp.f
xtb/pseudodiag.f90

This PR resolves a problem with the CMake install process if either `git` is not installed on the host machine or the sources have been downloaded and do not include the actual repository data.

CMake Update

---

meson.build
meson_options.txt

should fix #12, #39
requires meson 0.51

enables dynamic linking

---

xtb/argparser.F90

fixes https://github.com/grimme-lab/xtb_docs/issues/21

allow setting charge by --charge flag

---

xtb/cm5.f90
xtb/grad_core.f90
xtb/main_property.f90
xtb/scf_module.f90

Better CM5 calculation and gradient evalulation

---

xtb/molecule_reader.f90
xtb/molecule_writer.f90
xtb/symbols.f90
xtb/tbdef_molecule.f90

- D and T are synonyms for hydrogen

Allow saving of longer element symbols

---

assets/logo/xtb.svg
assets/logo/xtb_alt.svg

- convert text to path in svg files

Adjust svg of logos

---

.github/workflows/fortran-build.yml
.travis.yml
README.md
meson.build

- drop GH actions CI for Ubuntu (was unstable lately)
- use Ubuntu from Travis-CI instead

add support for Travis-CI

---

TESTSUITE/dftd4.f90
TESTSUITE/eeq_model.f90
TESTSUITE/gfn0.f90
TESTSUITE/gfn1.f90
TESTSUITE/gfn2.f90
TESTSUITE/peeq.f90
TESTSUITE/tbdef_molecule.f90
TESTSUITE/tbdef_wsc.f90
TESTSUITE/thermo.f90
src/coffee.f90
src/io/reader/ctfile.f90
src/io/reader/gaussian.f90
src/io/reader/genformat.f90
src/io/reader/pdb.f90
src/io/reader/xyz.f90
src/type/molecule.f90

- makes sure all fields are correctly populated

Change default constructor for molecular structure data

---

src/extern/mopac.f90

- also warn user that input has been patched

Patch user input for mopac to ensure gradient printout

---

.zenodo.json
README.md

- add zenodo badge
- add metadata for zenodo
- add conda-forge information

Release aftermath

---

.github/workflows/fortran-build.yml
.travis.yml

Pin meson 0.53.2

---

src/getsymnum.f90

Add S4, S8, T, Th and O pointgroups.

Add missing point groups and symmetry numbers

---

CMakeLists.txt
meson.build

Install GFN-FF parameter file

---

src/hessian.F90

Revert b8be0b8 for `hessian.F90` and reapply.

Regression: Fix parallelisation issues in hessian

---

.github/workflows/fortran-build.yml
TESTSUITE/gfnff.f90
src/gfnff/calculator.f90
src/gfnff/gfnff_eg.f90
src/gfnff/gfnff_ini.f90
src/gfnff/gfnff_ini2.f90
src/gfnff/gfnff_param.f90
src/gfnff/gfnff_setup.f90
src/gfnff/struc_converter.f90
src/main/setup.f90
src/prog/main.F90

Allow GFN-FF calculations without reading a parameter file

Default parameters for GFN-FF

---

TESTSUITE/eeq_model.f90
src/api/interface.f90
src/gfn0_calculator.f90
src/gfn1_calculator.f90
src/gfn2_calculator.f90
src/main/defaults.f90
src/solv/gbobc.f90

- forward printlevel to GBSA info printout
- redirect API output correctly by using env%unit
closes #187
closes #171
closes #160

Respect printlevel in API

---

TESTSUITE/CMakeLists.txt
TESTSUITE/meson.build
src/gfnff/frag_hess.f90
src/gfnff/gfnff_eg.f90
src/gfnff/gfnff_ini.f90
src/gfnff/gfnff_ini2.f90
src/gfnff/gfnff_setup.f90
src/gfnff/topology.f90
src/relaxation_engine.f90
src/restart.f90

- use environment for error handling
- use environment for IO
- use LAPACK wrappers for linear solvers
- fix OMP instructions

Cleanup for GFN-FF

---

src/gfnff/calculator.f90
src/gfnff/gfnff_eg.f90
src/gfnff/gfnff_ini.f90
src/gfnff/gfnff_ini2.f90
src/gfnff/gfnff_param.f90
src/gfnff/gfnff_setup.f90
src/gfnff/topology.f90
src/header.f90
src/main/setup.f90
src/restart.f90
src/type/anc.f90

Adding small improvements to the description of amides:
- scaling of amide N-H acidity parameter
- adjusting amide EEQ charges

GFN-FF v1.0.1

---

TESTSUITE/meson.build
meson.build
meson/meson.build

- allows xtb to be used as subproject

Update meson install procedure

---

src/restart.f90
src/type/iohandler.f90

- fix a logic error for finding opened files
- fix missing close statements
fixes #226

Fix IO errors introduced by recent changes

---

TESTSUITE/c_api_example.c
include/xtb.h
src/api/CMakeLists.txt
src/api/environment.f90
src/api/meson.build
src/api/utils.f90
src/api/version.f90
src/type/environment.f90

- add function to request API version from `xtb`.
- add semantic version to API (not `xtb` version number!).

Minor API update

---

TESTSUITE/dftd4.f90
src/disp/dftd4.f90
src/gfnff/gdisp0.f90
src/gfnff/gfnff_eg.f90
src/gfnff/struc_converter.f90
src/gfnff/topology.f90
src/main/property.f90
src/main/setup.f90
src/peeq_module.f90
src/read_gfn_param.f90
src/scf_module.f90
src/type/dispersion_model.f90
src/xtb/data.f90
src/xtb/dispersion.f90
src/xtb/gfn2.f90

- allows several calculator in parallel without messing up each others dispersion correction
- mainly important for API usage

Introduce local dispersion model object

---

TESTSUITE/c_api_example.c
TESTSUITE/eeq_model.f90
TESTSUITE/gfn0.f90
TESTSUITE/gfn1.f90
TESTSUITE/gfn2.f90
TESTSUITE/gfnff.f90
TESTSUITE/peeq.f90
src/api/calculator.f90
src/extern/turbomole.f90
src/gfnff/calculator.f90
src/gfnff/gfnff_eg.f90
src/main/defaults.f90
src/main/property.f90
src/main/setup.f90
src/peeq_module.f90
src/prog/main.F90
src/scc_core.f90
src/scf_module.f90
src/screening.f90
src/set_module.f90
src/solv/gbobc.f90
src/type/calculator.f90
src/type/dummycalc.f90
src/type/solvent.f90
src/xtb/calculator.f90

- remove usage of global `lgbsa` variable
- mainly concerning the API usage

Factor out solvation model

---

TESTSUITE/c_api_example.c
include/xtb.h
src/api/calculator.f90
src/api/results.f90
src/type/environment.f90

- also give access to max iterations and electronic temperature
- allow access to wavefunction

Add possibility to set numerical accuracy in API

---

src/prog/argparser.f90

Define allowed characters for flags

---

src/prog/main.F90
src/set_module.f90

Fix broken copy mode

---

src/solv/gbobc.f90

- add missing return in case of errors in GBSA init

Fix error handling in GBSA init

---

src/prog/main.F90
src/scan_driver.f90

Fix missing interface issue for GCC10

---

src/gfnff/gfnff_setup.f90

Fixed problem with reading charges from command line input

Reading charge input

---

src/main/setup.f90
src/type/environment.f90

- add rescue function to calculation environment

Allow to rescue failed wavefunction guesses

---

TESTSUITE/gfn2.f90
src/disp/dftd4.f90
src/scf_module.f90
src/xtb/hamiltonian.f90

- OMP parallelisation for ATM gradient
- faster integral gradient evaluation for finite systems
partly addresses #246

Regression: improve performance of gradients

---

TESTSUITE/gfnff.f90
TESTSUITE/meson.build
TESTSUITE/tests_peeq.f90
src/gfnff/calculator.f90
src/gfnff/gfnff_eg.f90
src/gfnff/gfnff_setup.f90

- fixed bug within GFN-FF total energy
- added GFN-FF/GBSA testsuite

GFN-FF energy with GBSA

---

include/xtb.h
meson.build

Preparation for next patch release

Bump xtb version number to 6.3.1

---

TESTSUITE/eeq_model.f90
TESTSUITE/gfnff.f90
src/gfnff/gfnff_eg.f90
src/main/defaults.f90
src/main/setup.f90
src/prog/main.F90
src/scc_core.f90
src/scf_module.f90
src/set_module.f90
src/setparam.f90
src/solv/gbobc.f90
src/type/solvent.f90

Implements the ALPB implicit solvation model.
- fix HB potential for EEQ based models (factor 2 in potential was missing)

Implement Analytical Linearized Poisson Boltzmann Model

---

.xtbrc
src/bias_path.f90
src/geoopt_driver.f90
src/optimizer.f90
src/prog/main.F90
src/relaxation_engine.f90
src/set_module.f90
src/type/setvar.f90

- improved metadynamics path finder
- new defaults for .xtbrc

Update metadynamics path finder

---

TESTSUITE/eeq_model.f90
src/main/setup.f90
src/set_module.f90
src/setparam.f90
src/solv/CMakeLists.txt
src/solv/gbobc.f90
src/solv/kernel.f90
src/solv/meson.build

- implement P16 interaction kernel for Born model
- fix ALPB energy expression

New interaction kernel for solvation model

---

TESTSUITE/gfn0.f90
TESTSUITE/gfn1.f90
TESTSUITE/gfn2.f90
TESTSUITE/gfnff.f90
TESTSUITE/peeq.f90
src/api/calculator.f90
src/api/interface.f90
src/api/results.f90
src/bias_path.f90
src/dynamic.f90
src/geoopt_driver.f90
src/gfnff/calculator.f90
src/gfnff/struc_converter.f90
src/hessian.F90
src/main/property.f90
src/main/setup.f90
src/mdoptim.f90
src/modef.f90
src/optimizer.f90
src/prog/main.F90
src/relaxation_engine.f90
src/scan_driver.f90
src/screening.f90
src/single.f90
src/type/CMakeLists.txt
src/type/calculator.f90
src/type/dummycalc.f90
src/type/meson.build
src/type/restart.f90
src/xtb/calculator.f90

- Fixes OMP broadcast for solvation model in calculator object

Regression: Parallelisation error for xTB hessians

---

src/api/calculator.f90

charptr is ignored in loadGFNXXTB_api

---

src/main/property.f90
src/solv/kernel.f90

- only print HB correction if array is allocated
- also diable parallelisation for P16 kernel
fixes #284

Fix GBSA printout

---

src/main/geometry.f90
src/main/property.f90

- use `sym` array directly instead of `toSymbol`
- avoid overflow of format fields by setting width to `i6`
- rework the WBO printout
fixes #195

Cleanup printouts

---

src/io/writer/turbomole.f90

- necessary for correct Turbomole compatibility

Fix name of $grad data group

---

man/xcontrol.7.adoc
src/main/property.f90
src/set_module.f90
src/setparam.f90

```
$thermo
imagthr=-20.0 # in cm-1
```

Allow adjusting imaginary inversion threshold

---

man/xtb.1.adoc
src/prog/main.F90
src/xhelp.f90

Signed-off-by: Hagen Neugebauer <hagen@thch.uni-bonn.de>

Added --json flag

---

man/xcontrol.7.adoc
src/hessian.F90
src/main/property.f90
src/set_module.f90
src/setparam.f90

New input
```
$thermo
scale=1.03
$end
```
and
```
$hess
scale=1.03
$end
```

Add scaling factor for frequencies in thermo/hessian calculation

---

src/extern/mopac.f90
src/type/dummycalc.f90

Signed-off-by: Philipp Pracht <pracht@thch.uni-bonn.de>

Read dipole moments for mopac interface calculations

---

README.md
assets/references.bib
src/xhelp.f90

- add WIREs CMS reference
- add page numbers to DFT-D4 reference
- fix QCEIMS reference for GFN2-xTB
- add references as bibtex to assets

Update references in README

---

.github/workflows/fortran-build.yml
.travis.yml

Release contraint on meson for build on OSX

---

man/xcontrol.7.adoc
man/xtb.1.adoc
src/CMakeLists.txt
src/constr.f90
src/fixparam.f90
src/getkopt.f90
src/gfnff/gfnff_eg.f90
src/header.f90
src/hessian.F90
src/meson.build
src/metadynamic.f90
src/prog/main.F90
src/prog/thermo.f90
src/set_module.f90
src/setparam.f90
src/xhelp.f90

- Implementation of the new bhess runtype for xtb

bhess runtype for xtb

---

README.md
assets/references.bib
man/xtb.1.adoc
src/prog/main.F90
src/set_module.f90
src/xhelp.f90

- retain default behaviour for --gbsa flag
- document the new commandline flags

Compatibility changes for solvation model

---

CMakeLists.txt
include/xtb.h
meson.build

Bump version number to release 6.3.3

---

.github/workflows/fortran-build.yml
.travis.yml
meson.build
src/hessian.F90

- add codecov upload
- change from buildtype release to debugoptimized as default
- exclude Intel oneAPI build

Fixup preprocessor directives in hessian

---

src/dynamic.f90
src/set_module.f90
src/type/setvar.f90

#345 
Signed-off-by: Philipp Pracht <pracht@thch.uni-bonn.de>

Allow MTD bias time constant adjustment via detailed input

---

src/gfnff/struc_converter.f90

Signed-off-by: Thomas Rose <39367840+Thomas3R@users.noreply.github.com>

Improved 2D=>3D converter struc_convert

---

meson/meson.build
src/aespot.f90
src/disp/dftd4.F90
src/grad_core.f90
src/hessian.F90
src/intgrad.f90
src/main/CMakeLists.txt
src/main/meson.build
src/main/property.F90
src/mctc/blas/CMakeLists.txt
src/mctc/blas/level1.F90
src/mctc/blas/level2.F90
src/mctc/blas/level3.F90
src/mctc/blas/meson.build
src/mctc/lapack/eigensolve.F90
src/mctc/mctc_global.F90
src/scc_core.f90
src/scf_module.F90
src/xtb/hamiltonian_gpu.f90
src/xtb/multipole.f90

- implement integral gradients on the GPU
- allow usage of cuBLAS for BLAS calls
- apply OpenACC for multipole populations

GPU portation of integral gradients

---

.github/workflows/fortran-build.yml

CI maintenance

---

src/set_module.f90

- maxcycles must be non-negative
- microcycles must be greater zero

Catch GIGO cases for optimizer setup

---

man/xcontrol.7.adoc
src/bias_path.f90
src/constrain_param.f90
src/dynamic.f90
src/fixparam.f90
src/gfnff/calculator.f90
src/hessian.F90
src/metadynamic.f90
src/prog/main.F90
src/set_module.f90
src/type/dummycalc.f90
src/type/setvar.f90
src/xtb/calculator.f90

- use --bias-input <xyz> for input

Allow reading RMSD bias from file

---

meson.build
meson/meson.build

Add tests for NVHPC signature and treat them similar to PGI compilers.

Support NVHPC compilers in meson build

---

CONTRIBUTING.md
README.md

- update list of contributors
- move contributor list to README for visibility
- remove the gitter chat link
- add a clarification for LGPL licensing of submitted patches

Update README to include contributor list

---

src/intgrad.f90
src/xtb/halogen.f90
src/xtb/hamiltonian.f90

- use runtime schedule if possible

Update OpenMP pragmas

---

src/hessian.F90
src/main/property.F90

Signed-off-by: Marcel Müller <marcel.mueller@thch.uni-bonn.de>

Minor corrections in units of output (amu to km/mol) and nicer superscripts of cm-1.

---

README.md
man/xtb.1.adoc
src/xhelp.f90

Update help printout

---

src/freq/project.f90

Switched source and target matrix in symmetric rank k update.

Correctly setup projector matrix

---

TESTSUITE/gfnff.f90
src/gfnff/calculator.f90
src/gfnff/gfnff_ini.f90
src/header.f90

- fixing the error within the distance assignment above the given threshold
- now writing 'gfnff_charges' in analogy to the xtb methods

Fixing topological charges

---

TESTSUITE/gfnff.f90
src/gfnff/CMakeLists.txt
src/gfnff/calculator.f90
src/gfnff/gfnff_eg.f90
src/gfnff/gfnff_ini.f90
src/gfnff/gfnff_ini2.f90
src/gfnff/gfnff_param.f90
src/gfnff/gfnff_setup.f90
src/gfnff/meson.build
src/gfnff/neighbourlist.f90
src/gfnff/topology.f90
src/header.f90
src/hessian.F90
src/main/setup.f90
src/restart.f90
src/type/restart.f90

Closes https://github.com/grimme-lab/xtb/issues/361
Preview: https://github.com/awvwgk/xtb/suites/2538375022/artifacts/55088541
cc @sespic @Thomas3R

Cleanup neighbour list data in GFN-FF topology

---

README.md
src/scf_module.F90
src/xhelp.f90

Closes https://github.com/grimme-lab/xtb/issues/451 based on suggestion of @awvwgk

Change unconverged SCF to error

---

CMakeLists.txt
meson.build

Bump version to 6.4.1

---

man/xcontrol.7.adoc
src/set_module.f90

Fixes https://github.com/grimme-lab/xtb/issues/486

Fix gridfile keyword

---

README.md
assets/references.bib
src/xhelp.f90

Closes https://github.com/grimme-lab/xtb/pull/479

Add reference for ALPB and GBSA model

---

src/dynamic.f90

Fix overflow of array for long dynamics

---

src/gfnff/gfnff_ini.f90
src/gfnff/gfnff_setup.f90

- only use PDB charges from residues if they match system charge
(previous behaviour: PDB charges always overwrite total system charge)

Update handling of charges in GFN-FF

---

src/gfnff/topology.f90
src/main/json.f90
src/prog/main.F90

Signed-off-by: Thomas Rose <39367840+Thomas3R@users.noreply.github.com>

You can now print GFN-FF topology lists

---

README.md
src/xhelp.f90

- @hoelzerC adding you to the author list
- @cbannwarth adding a link to your homepage

Update author list in README and program header

---

README.md
src/CMakeLists.txt
src/api/calculator.f90
src/api/interface.f90
src/gfnff/calculator.f90
src/gfnff/gfnff_ini.f90
src/gfnff/struc_converter.f90
src/gfnff/topology.f90
src/main/setup.f90
src/meson.build
src/oniom.f90
src/prog/main.F90
src/prog/topology.f90
src/set_module.f90
src/setparam.f90
src/topology.f90
src/type/calculator.f90
src/type/topology.f90
src/xhelp.f90
src/xtb/calculator.f90
test/unit/test_gfn0.f90
test/unit/test_gfn1.f90
test/unit/test_gfn2.f90
test/unit/test_gfnff.f90
test/unit/test_hessian.f90
test/unit/test_peeq.f90

Add Oniom calculator

---

src/eeq_model.f90
src/hessian.F90
src/printout.f90
src/prog/main.F90
src/scf_module.F90

Fixes https://github.com/grimme-lab/xtb/issues/456

Fix hessian calculations for single atoms

---

src/constrain_param.f90

Catch out-of-bounds indexing for constraints

---

CMakeLists.txt
meson.build

Release 6.5.0

---

README.md
meson.build
meson/meson.build

Some required fixes to make the build with meson on Windows run smoother.

Fixes for Windows build

---

test/unit/meson.build

Allow finding of installed test-drive dependencies

---

src/prog/main.F90

Closes https://github.com/grimme-lab/xtb/issues/627

Calculate number of electrons before restart

---

src/type/molecule.f90

Closes https://github.com/grimme-lab/xtb/issues/628

Copy number of bonds for writing

---

src/api/molecule.f90

Declare optional arguments in C-API

---

.github/workflows/fortran-build.yml
meson.build
meson/meson.build

Closes https://github.com/grimme-lab/xtb/issues/402

Fix MKL finding with Intel 2021 and newer

---

src/extern/orca.f90

Fixes Orca sanity check

---

src/type/iohandler.f90

Signed-off-by: cplett <82893466+cplett@users.noreply.github.com>

Bugfix for compiler fortran-2022.2.0

---

src/docking/search_nci.f90

Signed-off-by: cplett <82893466+cplett@users.noreply.github.com>

Bugfix for aISS when using multiple constraints

---

src/gfnff/gfnff_eg.f90

Fixed a bug in the GFN-FF hydrogen bonding, described in issue #729

Fix GFN-FF Bug issue #729. HB Carbonyl and Nitro case.

---

test/unit/test_gfn2.f90

Adds a unit test for the error that was fixed in #720.

Added test to check PCEM I/O

---

man/xcontrol.7.adoc
src/dynamic.f90
src/set_module.f90
src/setparam.f90

Add option to force writing of mdrestart files.

---

.github/workflows/fortran-build.yml

Update workflows to meson 0.62.0

---

man/xtb.1.adoc
src/main/setup.f90
src/prog/main.F90
src/tblite/calculator.F90
src/xhelp.f90

- Simple initial commit for spin-polarization
Signed-off-by: haneug <hagen@thch.uni-bonn.de>

Spin-polarization in xTB

---

src/CMakeLists.txt
src/meson.build
src/prog/main.F90
src/vertical.f90
test/unit/CMakeLists.txt
test/unit/main.f90
test/unit/meson.build
test/unit/test_vertical.f90

fix fukui and migrate to vertical.f90

---

src/extern/orca.f90

Fixes external Orca calculation.

---

README.md
src/oniom.f90
src/xhelp.f90

update `oniom.f90` w.r.t. https://doi.org/10.1039/D3CP02178E publication

add ONIOM references and update derived mode

---

README.md

The URL was giving a 404. This fixes that

Update URL to docs in README.md

---

src/gfnff/gfnff_ini.f90
src/gfnff/gfnff_setup.f90

Fix manual override of charge for pdb files.

---

src/docking/search_nci.f90

If two different input formats are used, the one of the larger structure is taken.

aISS writes best structure in file format of input

---

CMakeLists.txt

This option has been in the meson but not in the CMake.

add CMake option INSTALL_MODULES

---

man/xtb.1.adoc

add description of xtbtopo.mol

---

src/constrain_param.f90

add option to constrain all atoms:
```
$constrain
atoms: all``

constrain all atoms

---

.github/workflows/stale_label.yml

change the workflow to create a comment, when pr/issue is marked as **stale**.

fix stale handling

---

man/xtb.1.adoc
src/prog/main.F90
src/tblite/calculator.F90
src/xhelp.f90

calculate CEH charges via tblite interface.
Small summary:
1. `get_ceh` procedure to obtain the charges from the library.
2. write the charges to **ceh.charges**.
3. update the manuals.

add --ceh flag

---

src/vertical.f90
test/unit/test_vertical.f90

As discussed in #1041 I change the sign of the Fukui indices (once again).

Change sign of Fukui indices 

---

src/docking/param.f90
src/docking/search_nci.f90
src/iff/iff_prepare.f90
src/prog/dock.f90
test/unit/test_docking.f90

- Bug fixes for the aISS docking module related to #1078 and #1079 
- Ensuring that the correct charges and coordination numbers are used for the GFN1-xTB and GFN2-xTB calculations during the aISS docking algorithm

aISS update

---

README.md
assets/references.bib

- updated `README.md` and `references.bib` with appropriate PTB citations

Include PTB in README.md and references.bib

---

src/prog/main.F90

Fix double print of ancopt header

---

meson/meson.build

Find and also validate usability of lapack and blas libraries.

Better support for finding custom lapack implementaion

---

src/docking/search_nci.f90

The final geometry optimizations during the aISS docking can now be skipped with the `--nfinal 0` flag.

Possibility to skip the geometry optimizations during aISS docking

---

src/gfnff/gdisp0.f90

Avoid zero division in GFNFF

---

cmake/CMakeLists.txt
src/gfnff/gfnff_eg.f90
src/main/json.F90
src/scc_core.f90
test/unit/test_docking.f90

This patch adds support of LLVMFlang (tested with flang-trunk). With some extra patches of 3rd-party deps, all tests are passing without OpenMP. OpenMP builds are not tested yet.

Add initial support of LLVMFlang

---

src/gfnff/calculator.f90

Added sasa printout for GFN-FF

---

src/prog/main.F90
src/tblite/calculator.F90

Fix passing `--iterations` to tblite

---

src/api/utils.f90

Proper length for lhs

---

src/extern/mopac.f90

- implemented some exits on fail checks
- we don't expect gradients for atoms
- closes #1267

Avoid infinite `mopac` loops 

---

.github/workflows/fortran-build.yml
README.md
meson.build

See https://github.com/mesonbuild/meson/issues/14528
See https://github.com/mesonbuild/meson/issues/14532
See https://github.com/mesonbuild/meson/pull/14549

Avoid meson 1.8.0

---

src/optimizer.f90

Fixes #1277 
Other issues related to gfortran 15.1 still may be observed.

Fix commas in optimizer

---

src/extern/orca.f90

Fixes a bug as mentioned in #1308 with a better sanity check. This now checks the orca binary contents for the keyword "SCF" as this should be specific enough to discriminate it from the GNOME screen reader binary.
Also formatted the source file.

ORCA executable check vs gnome screen reader using SCF keyword in binary

---

src/prog/main.F90

This PR removes warning introduced in #1327

Use dummy logical variable
