TESTSUITE/cpp_api_example.cpp
TESTSUITE/dftd4.f90
TESTSUITE/eeq_model.f90
TESTSUITE/gfn0.f90
TESTSUITE/gfn1.f90
TESTSUITE/gfn2.f90
TESTSUITE/peeq.f90
include/xtb.h
meson.build
xtb/c_api.f90
xtb/calculator.f90
xtb/gbobc.f90
xtb/geometry_reader.f90
xtb/header.f90
xtb/program_main.f90
xtb/version.f90

Some maintenance and bugfixes (:beetle:) for the release aftermath. This changes the internals of the C-API (exposing a few bugs) and connects the GBSA model with the API.
This pull request is not breaking API compatibility.

GBSA refactoring and API fixes

---

TESTSUITE/cpp_api_example.cpp
meson.build

should fix #8
- adjust thresholds for assertions on the cluster in Bonn

require C++11 for nullptr support in the API-test

---

.github/dco.yml
CONTRIBUTING.md
README.md

Since we already took the step to go open source, we should also commit to the idea of an open source community. I wrote up contributing guidelines for `xtb`.
One open question: should we enforce a Developer Certificate of Origin (DCO, see https://probot.github.io/apps/dco/ for an easy way to implement it) with `xtb`? It seems pretty standard for larger projects and is more developer friendly than requiring to sign a Contributor License Agreement (CLA).

add contribution guidelines to xtb

---

TESTSUITE/thermo.f90
xtb/dtrafo.f90
xtb/hlex.f90
xtb/local.f90
xtb/main_json.f90
xtb/main_property.f90
xtb/program_main.f90

- pass geometry as molecule class
- remove array dimensions since they are passed by basis set object
- make dtrafo a module to check dummy arguments
- fix missing arguments in sao2cao trafo :beetle:

refactored property printout routines

---

TESTSUITE/assertion.f90
TESTSUITE/tbdef_atomlist.f90
TESTSUITE/tests_peeq.f90
meson.build
xtb/constrain_param.f90
xtb/main_property.f90
xtb/set_module.f90
xtb/tbdef_atomlist.f90

- ~replace all lists with atom lists~

Atomlist class

---

xtb/scc_core.f90

for temperatures smaller 0.1 K the electronic entropy is not initialized in the SCC iterator (should be zero), nevertheless it is always added to the electronic energy afterwards.
This adds an explicit initialization for the electronic entropy to avoid issues in the future.
Thanks to Oliver Unke for reporting this.

fix missing initialization of electronic entropy

---

python/xtb/calculators.py
python/xtb/solvation.py

raise exception if calculator without PBC is called with periodic input

---

TESTSUITE/geometry_reader.f90
TESTSUITE/tests_peeq.f90
mctc/mctc_resize_arrays.f90
meson.build
xtb/dynamic.f90
xtb/molecule_reader.f90
xtb/molecule_writer.f90
xtb/optimizer.f90
xtb/program_main.f90
xtb/relaxation_engine.f90
xtb/tbdef_buffer.f90
xtb/tbdef_fragments.f90
xtb/tbdef_molecule.f90
xtb/tbdef_topology.f90
xtb/tbmod_file_utils.f90

With this PR we aim to restructure the IO for molecular structure information. Currently every driver is implementing its own reader and writer routines, also most of the meta data from the input is dropped or not stored in a suitable place close to the molecular structure.
- ~generic reader from file name~ (handled by caller)
- ~generic writer to file name~ (handled by caller)
- ~allow additional tags on bonds/angles~ (information produced in `xtb`)
closes #26 
- addresses R1 -> error on 2D structure
- addresses R3 -> adds error for H atom query, otherwise GIGO
- addresses R5 -> checks for charges, ignores radical information
- ignores R2, R6 (not in scope for the PR, see #34)
- ignores R4 (not in scope for `xtb`)
closes #28 (adds error for H atom query)

New IO routines for molecular structure information

---

xtb/program_main.f90

fixes #47, introduced by 653a4c3

Repair center of mass shift

---

xtb/program_main.f90

no more additional help printout in verbose mode (use `--help` or `-h` instead), since it just clutters the screen and does not add any useful information.

remove help printout for verbose runs since it clutters the screen

---

TESTSUITE/dftd4.f90
TESTSUITE/peeq.f90
xtb/dftd4.f90

- fixes i-i' scaling factor (was 1, should be 1/2) :beetle:
- update `dftd4.f90` with DFT-D4 code
Severe error for GFN0-xTB under PBC (too attractive interactions).
related: https://github.com/dftd4/dftd4/pull/24

Bugfix: periodic DFT-D4 calculations had wrong i-i' contribution

---

xtb/set_module.f90

fixes #66
The easy solution, just catch invalid temperatures while parsing the input and avoid headaches later.

Error if no valid temperatures are given in thermo input

---

xtb/optimizer.f90
xtb/set_module.f90
xtb/setparam.f90

Read-in of previous calculated hessians is somewhat annoying and shouldn't be the default.

Hessian read-in mode for RF optimizer

---

xtb/program_main.f90

fixes #74
Distance threshold is set to 1.0e-9, which should be far beyond reasonable for any geometry.
```
########################################################################
########################################################################
#ERROR! XTB REFUSES TO CONTINUE WITH THIS CALCULATION!
abnormal termination of xtb
```
With `--strict` the run is killed immediately at:
```
#ERROR! Found *very* short distance of  0.000E+00 for S1-Ar2
abnormal termination of xtb
```
Note: The API does not perform such checks... hopefully they are not necessary there.

add cold fusion check to xtb

---

meson.build
python/setup.py

Staging for release v6.2.2, requires https://github.com/grimme-lab/xtb/milestone/1 to be finished.

Preparation for release of xtb version 6.2.2

---

meson.build

Adding  `-D_Float128=__float128` fixes compilation issues with `symmetry/symmetry_i.c` on OpenSUSE.
Thanks to @jens-vasp for pointing this out.

OpenSUSE specific fix for C-source code

---

README.md
assets/logo/README.md
assets/logo/xtb.svg
assets/logo/xtb_alt.svg

This started as a fun project to create a “logo” for `xtb` and was subsequently used on posters which made it kind of official. This PR adds the two `svg` files for the “logo” to the official repository making it really official.
Have a look [here](https://github.com/awvwgk/xtb/tree/xtb-logo/assets/logo) for a depiction of the “logo” and [a way to use them](https://raw.githubusercontent.com/awvwgk/xtb/xtb-logo/assets/logo/README.md) in GitHub flavoured Markdown.

Do we need a logo?

---

meson.build

A copy and paste error in the testsuite.

check for flake8 instead of pylint in flake8 test

---

.github/workflows/fortran-build.yml
README.md
TESTSUITE/gfn0.f90
TESTSUITE/gfn1.f90
TESTSUITE/gfn2.f90
TESTSUITE/meson.build
TESTSUITE/peeq.f90
meson.build
meson_options.txt
xtb/argparser.F90
xtb/c_api.f90
xtb/calculator.f90
xtb/gfn0_calculator.f90
xtb/gfn1_calculator.f90
xtb/gfn2_calculator.f90
xtb/grad_core.f90
xtb/hessian.F90
xtb/modef.f90
xtb/molecule_reader.f90
xtb/program_main.f90
xtb/scc_core.f90
xtb/scf_module.f90
xtb/screening.f90
xtb/tbdef_atomlist.f90
xtb/tbdef_fragments.f90
xtb/tbdef_param.f90
xtb/tbmod_file_utils.f90

hopefully fixes #11
also fixes #12 when we are running the CI on OSX!
[![Build Status](https://github.com/awvwgk/xtb/workflows/CI/badge.svg)](https://github.com/awvwgk/xtb/actions)
This is work in progress and not my highest priority. If you think you can help out here, feel free to open a PR on this PR :)

Enable Build with GCC

---

xtb/local.f90
xtb/main_property.f90
xtb/peeq_module.f90
xtb/scc_core.f90
xtb/scf_module.f90

makes Wiberg bond order calculation finally independent from the printlevel.
Resolves 1. and 2. point of #98.

Fix Wiberg bond order calculation

---

cmake/Files.cmake
meson.build
scripts/xtb-gaussian
xtb/molecule_reader.f90
xtb/molecule_writer.f90
xtb/output_writer.f90
xtb/program_main.f90
xtb/symbols.f90
xtb/tbdef_molecule.f90
xtb/tbmod_file_utils.f90

Allows `xtb` to read new file formats. Solves #95 on the `xtb` level.

Support more file formats for input/output

---

xtb/eeq_model.f90

was previously set to zero, but does not hold true for periodic systems and charges systems

calculate EEQ energy for one atom systems

---

man/man7/xcontrol.7.txt

Removes deprecated run mode from `xcontrol(7)` man page.

Remove siman from xcontrol(7)

---

xtb/molecule_writer.f90

Order of sign and number was wrong in output PDB

Fix PDB output writer for partial charges on atom sides

---

xtb/molecule_writer.f90

Fix overflow introduced in #124 for negative charges.

Fix PDB writer to not overflow the charge record

---

xtb/main_property.f90

Fix sign error in GFN1-xTB Mulliken charge printout

---

xtb/main_json.f90

- was also wrong type (real instead of string)
fixes #129

Fix printout of xtb version number in json dump

---

meson.build
meson_options.txt

In case the python wrapper should not be tested by meson add `-Dpython=false` to the configuration options.

make python module optional

---

meson.build
meson_options.txt

Rescue build configuration if build is not in a git repo, i.e. downloaded as archive. `-Dbuild_name` option can be used to override the default value in case of specific recognizable builds like AUR, conda and so on.

Change configuration of version number with commit

---

meson/meson.build
meson/openblas_lapack_test.f90

The configuration previously used only the `find_library` method of the compiler object in meson. With this PR meson will first try the high-level `dependency` function and than fall back to the `find_library` method.
Additionally
- error check if Intel builds should be statically linked without MKL
- check if OpenBLAS library is providing a LAPACK API

Use dependency in meson instead of find_library

---

.github/workflows/fortran-build.yml

Should fix the increasingly encountered CI errors with GitHub actions. This PR will not revert the migration to Travis-CI for the Ubuntu build.
See https://github.com/actions/checkout/issues/23 for details.

Update GitHub actions/checkout to v2

---

python/setup.py
src/prog/main.f90
src/type/environment.f90

This PR enables the strict mode (`--strict`) for the new error handling environment.
In case a warning occurs it is raised as error, but the environment will only return at the next higher level or a checkpoint.

Allow strict mode for new environment

---

src/hessian.F90

- declare strain derivs in omp as private

Fix: Parallelisation of numerical Hessian

---

cmake/Files.cmake
src/constrain_param.f90
src/mctc/symbols.f90
src/type/identitymap.f90
src/type/meson.build
src/type/molecule.f90

This PR introduces an unique id for each species in the molecular structure. This enables:
1. storing element specific data in a dense way
2. convenient setting of values for whole groups of atoms with the same id
With the definition here the identity is defined by unique element symbols, so the user can produce additional identities by using slightly mangled symbols, *i.e.* `C`, `c` and `C_` are different species in w.r.t. the id, but all map to the atomic number 6. All internal initialization will use the atomic number, but user initialization can make use of the id by specifying the respective symbol.

Introduce chemical identity

---

scripts/otool_xtb
src/io/writer/turbomole.f90

Fixes #153
- adds a script to wrap `xtb` 6.2.3 binary (also added to the v6.2.3 release tag)
- fixes the printout in `xtb` so it matches the expectation of the reader in Orca

Fix Orca 4.2.1 incompatible energy printout

---

src/io/reader/ctfile.f90
src/io/writer/ctfile.f90

Quick fix for #158
Saves the input bond order from the connection table and echos it when writing mol or sdf output.

Fix: save bond orders from ctfiles

---

src/slater.f90

Add the STO-6G expansion coefficients for 6s and 6p Slater type orbitals into six primitive Gaussian orbitals.
Thanks to @pprcht for spotting this regression.

Regression: Missing expansion coefficients for 6s and 6p functions

---

cmake/CMakeLists.txt

Unfortunately the GH actions CI will fail due to an issue with meson 0.54, but this is not affected by this PR.

Properly rename libraries compiled by CMake

---

src/CMakeLists.txt
src/main/property.f90
src/meson.build
src/topology.f90

discussed in #158
closes #34
For this algorithm we
1. generate a bond topology from the Wiberg bond orders
2. translate the WBO topology to a sorted neighbourlist
3. translate the input topology to a sorted neighbourlist as well
4. compare those neighbourlists w.r.t. length, number of neighbours, actual neighbours and bond orders (stored somewhat hacky in the Wigner–Seitz weight)
This allows to work even on differently sorted bond topologies. In case we fail, or we do not have an input topology (xyz or coord input), we write the new topology as connection table to `xtbtopo.mol` or `xtbtopo.sdf`. The input topology will not be amended by this check.
order | WBO | C-N-O
--- | --- | ---
1 | 0.3 to 1.3 | 0.3 to 1.2
2 | 1.3 to 2.3 | 1.4 to 2.3
3 | greater 2.3 | greater 2.3
4 | | 1.2 to 1.4 …

Implement comparison between topologies

---

src/prog/main.F90

Revert initialization of detailed input file with 'xcontrol'

Regression: default detailed input should be geometry input

---

man/man7/xcontrol.7.txt
src/io/writer/turbomole.f90
src/main/property.f90
src/set_module.f90
src/setparam.f90

Implement printout for normal modes in Turbomole format.
Use with detailed input
```
$write
vib_normal_modes=true
$end
```
Will create a file `vib_normal_modes` for `--hess` and `--ohess` runs containing the `vibrational` data group as
```
$vibrational normal modes
1  1   0.0627745744  -0.0281330227  -0.0322002988  -0.0201372051  -0.0288325538
1  2   0.0238768339  -0.0000093539   0.0000128526  -0.0000009103  -0.0000046597
1  3  -0.0000059296   0.0000044965   0.0000114170  -0.0061363907  -0.0000481400
1  4  -0.0335000536   0.0000767417   0.0325447599  -0.0000285850  -0.0152998377
1  5   0.0318889379  -0.0359649174   0.0728160919   0.0679550961  -0.0006859928
1  6   0.0803744515  -0.0002999631   0.0000629725   0.0000082075  -0.1128229229
1  7   0.1044632519  -0.0000051232  -0.0278467442 …
```

Add Turbomole vibrational modes format

---

man/man7/xcontrol.7.txt
src/hessian.F90
src/set_module.f90
src/setparam.f90

Allow printing a DFTB+ compatible `hessian.out` file which can be read in *e.g.* with the `modes` program.
To run:
```bash
printf "\$write\n hessian.out=true\n\$end\n" > hess.inp
xtb --gfnff --hess --input hess.inp <geometry>
```
@pecchia Let me know if this works for you.

Implement DFTB+ style hessian.out

---

src/prog/CMakeLists.txt
src/prog/meson.build
src/prog/primary.f90
src/prog/submodules.f90
src/prog/thermo.f90
src/prog/topology.f90

Allow to generate a force field topology without a complete GFN-FF calculation.
Usage
```
xtb topo <geometry>
...
ls gfnff_*
gfnff_topo
```

Add topology submodule

---

src/gfnff/gfnff_param.f90

Fix setup of covalent radii when reading gfnff parameter file

Fix initialization when reading GFN-FF parameters

---

meson/meson.build
meson_options.txt

Deletes the `-Dstatic` option, separates `mkl`, `mkl-static` (default) and `mkl-rt` as linear algebra backends.
`la_backend` | Description
--- | ---
`mkl` | link shared MKL libraries, produce dynamically linked binaries
`mkl-static` | link static MKL libraries, produce statically linked binaries
`mkl-rt` | link real time MKL library, produce dynamically linked binaries
*Precompiled binaries will be provided with Intel 17 and `mkl-static`.*
`mkl-static` is included for convenience and because it is the default for distribution of `xtb`. 
Following setup is equivalent to `mkl-static`:
```
meson setup build -Dla_backend=mkl -Dfortran_link_args=-static
```
To link static binaries with other backends the `-Dfortran_link_args=-static` flag should be provided in the configuration step.
Fixes …

Separate logic for MKL linking from static option

---

src/geoopt_driver.f90
src/optimizer.f90
src/prog/main.F90

- recover error in geoopt driver to perform a diagnostic SP
- report last failed structure before termination:
```
last geometry written to: xtblast.coord
########################################################################
[ERROR] Program stopped due to fatal error
-5- Geometry optimization failed
-4- xtb_geoopt: Trying to recover from failed geometry optimization
-3- xtb_geoopt: Geometry optimization did not converge
-2- optimizer_ancopt: Could not relax structure
-1- optimizer_relax: internal rational function error
########################################################################
abnormal termination of xtb
```

Rescue failed geometry optimization

---

.travis.yml
meson.build
meson/meson.build

Intel is providing compilers and MKL for apt, the PR enables the Intel oneAPI on Travis CI to build `xtb`.
For more details see: https://software.intel.com/content/www/us/en/develop/articles/oneapi-repo-instructions.html#aptpkg
Could be used to continuously compile and release `xtb` binaries, maybe together with the CentOS8 docker image: https://hub.docker.com/r/intel/oneapi-hpckit

Setup CI build with Intel compilers

---

src/generate_wsc.f90
src/gfnff/calculator.f90
src/type/dummycalc.f90
src/type/molecule.f90
src/xtb/calculator.f90

The patch adds explicit interfaces for `generate_wsc`, as well as fixes a bug in `generate_wsc` that causes test failures on a number of architectures.

Add interfaces to generate_wsc

---

src/io/writer.f90

Output files aren't currently flushed, which makes it painstaking to follow progress of the optimization in xtb.
This PR adds `flush(unit)` at the ends of writer functions, allowing one to visualize e.g. `xtbopt.log` with Jmol or other programs.

Flush output at end of write functions

---

src/io/reader/ctfile.f90
src/io/writer/ctfile.f90
src/prog/main.F90

- prefer CHG blocks over entries in the atom charge fields
- raise warning in case the molecular charge is overwritten
- fix spacing in CHG block
closes #253

Correct reading/writing of charge in CT files

---

assets/meson.build
assets/templates/env-module.tcl

Add tcl Environment Module

---

src/dynamic.f90

In case the input was PDB, a trajectory can be printed as multiple PDB models to one file. While neither pretty nor efficient it allows to visualise the trajectory in most editors supporting PDB.
- ~~write optimization log as PDB as well~~ (scope narrowed a bit)
first part for #211

Enable printing of PDB trajectories

---

TESTSUITE/gfn0.f90
TESTSUITE/gfn1.f90
TESTSUITE/gfn2.f90
TESTSUITE/molstock.f90
meson.build
meson/README.adoc
src/read_gfn_param.f90

- default optimization should be `-O2` for GCC (`-O3` is fine for Intel, but leads to failures with GCC)
- add a note about compiler optimization to meson guide

Adjust buildoptions for GCC 

---

src/api/calculator.f90

- deallocate `TSolvModel` object in calculator (setting `lSolv=.false.` is not sufficient anymore)

Allow to unset the solvation model in the API

---

CMakeLists.txt
include/xtb.h
meson.build

- bump version number to 6.3.2
- use `XTB_API_SUFFIX__*` to refer to the API version rather than to the `xtb` version number

Release version 6.3.2

---

src/main/setup.f90

Allow `"gas"` and `"vac"` as keywords for not-solvation

New keywords for not-solvation

---

.travis.yml
TESTSUITE/gfnff.f90
TESTSUITE/meson.build

The non-deterministic failure of the GFN-FF in #276 seems to be related to the way meson is running unit tests with `MALLOC_PERTURB_`, see https://mesonbuild.com/Reference-manual.html#test. I think it might be a better to keep the default behaviour of meson as it shows flaws in the test suite rather than in production runs, but we will just disable it for GFN-FF related testing for now.
While this certainly does not fix the underlying (and still unknown) issue it will hide it in the CI.
closes #276

Reproducable GFN-FF unit tests

---

src/xhelp.f90

Minor correction to help options output text
iteration corrected to iterations

typo correction in the help output. iteration should be iterations

---

TESTSUITE/meson.build
src/gfnff/gfnff_eg.f90

Bug #276 contained a rare invalid memory access bug, because part of a matrix was not zero initialized.
The issue was a missing initialization of the diagonals of a distance matrix in `gfn_eg`. This fixes the bug and removes invalid memory access in rare cases. It also turn memory perturbation on again by reverting part of a previous commit.
Unit tests run through, results.
```
Ok:                 8900
Expected Fail:      300 
Fail:               0   
Unexpected Pass:    0   
Skipped:            300 
Timeout:            0   
```
Before merging, the following has to be considered:
The loop I changed actually collects some ids in an array called
`d3list`
I guess that this is present to collect the ids, which should be considered for d3 dispersion. I therefore did not extend the loop itself …

Access of uninitialized memory in gfn_eg. Fixes #276

---

CMakeLists.txt

At present the `project` in CMake doesn't specify the used languages, which results in the default being used, which is C and C++. However, a C++ compiler is not needed for xtb.

Specify used languages in CMake project (no C++ needed).

---

CMakeLists.txt
README.md
cmake/CMakeLists.txt
cmake/README.adoc
meson/README.adoc
meson_options.txt

- create SOVERSION and VERSION postfixed shared object
- use GNUInstallDir to get installation directories consistent to meson
- Update READMEs about installation configurations
closes #311, #312, #313

Make CMake behave similar to meson

---

src/solv/CMakeLists.txt
src/solv/input.F90
src/solv/meson.build

- PGI 20.7 cannot use constructors including deferred length character variables, this PR includes an optional wrapper to mitigate the issue until it is fixed in the PGI compilers
Fixes #325

Provide a workaround wrapper for PGI builds

---

src/extern/mopac.f90

- read `HEAT_OF_FORMATION:KCAL/MOL` instead of `TOTAL_ENERGY:EV` for total energy

Adjust MOPAC interface

---

src/bias_path.f90

```
PGF90-S-0000-Internal compiler error. transform_call:Array Expression can't be here   79130  (../src/bias_path.f90: 162)
Lowering Error: bad ast optype in expression [ast=79582,asttype=12,datatype=0]
PGF90-F-0000-Internal compiler error. Errors in Lowering       1  (../src/bias_path.f90: 195)
PGF90/x86-64 Linux 19.10-0: compilation aborted
```
Fixed in PGI 20.1

Workaround for PGI 19.7 ICEing on norm2

---

TESTSUITE/CMakeLists.txt
TESTSUITE/gfnff.f90
TESTSUITE/meson.build
TESTSUITE/molstock.f90
TESTSUITE/tests_peeq.f90
src/gfnff/gfnff_setup.f90

Added the initialization of the fragment charge qfrag for the sdf and mol file case as proposed by @awvwgk .
This seems to resolve the problem. I tested it for the given file.sdf, a self made molfile and for some few charges each.

Bug fix: Initialize qfrag for SDF and mol case in gfnff_setup  Resolves: #322

---

src/mctc/systools.F90

This PR solves a long-standing issue in xtb, mysterious crashes on the build systems in the check phase. After several hours of debugging, I've finally found the root problem.
The mysterious crashes were always due to `Fortran runtime error: Zero-length string passed as value to get_environment_variable.`
The problem is triggered whenever you read the value for a variable that is not set. In this case the length is 0, which is properly allocated, but then the GNU Fortran library crashes when the variable is read since the result array has zero length.
The problem was triggered in the tests, since neither CMake nor Meson sets `XTBHOME`.

Fix crash in get_environment_variable()

---

src/hessian.F90

`#ifndef __PGIC__` does break parallelisation with other compilers

Remove check for __PGIC__ preprocessor in hessian

---

src/hessian.F90

Fixes failing hessian runs with Intel 17 on Cluster in Bonn

Guard time estimate printout in hessian with omp critical

---

src/constrain_param.f90
src/constrain_pot.f90
src/scanparam.f90
src/type/setvar.f90

```
$constrain
DISTANCE: 1, 2, auto, 4
$end
```

Allow adjusting of spring exponent

---

man/xcontrol.7.adoc
src/gfnff/data.f90
src/gfnff/gdisp0.f90
src/gfnff/gfnff_eg.f90
src/gfnff/gfnff_setup.f90
src/hessian.F90
src/set_module.f90
src/setparam.f90

- add $gfn/dispscale=<real> keyword
- store dispersion scaling in calc%param%dispscale
- pass dispersion scaling to d3_gradient routine of GFN-FF

Allow scaling of dispersion energy in GFN-FF 

---

src/mctc/filetypes.f90

As of now, if the initial geometry file is given as a relative path without any / in it, the basename is empty. For example, running 
xtb Gau-1234.EIn
generates an output file at `.EOu` as opposed to the correct `Gau-1234.EOu`, because the basename is not detected and defaults to the empty string. Running
xtb ./Gau-1234.EIn
works fine however.
This very small PR fixes this by explicitly setting the position of the / (when it's not there) to just before the beginning of the filename (pos 0).

Fixes incorrect basename detection when path does not contain '/'

---

src/extern/turbomole.f90
src/relaxation_engine.f90

For runtype ``-tm``:
- if file `gradient` is found, read gradient and geometry
- if geometry matches current geometry, use gradient, don't perform calculation
- if geometry does no match, perform calculation

Try to use cached Turbomole results

---

src/optimizer.f90

- change gradient convergence from 0.002 to 0.0025 for optimization level lax

Adjust optimization thresholds for DCOSMO-RS level

---

src/prog/main.F90

- also adjust default temperature for FOD to 5000 K (more reasonable default)

Fix key-mismatch for setting electronic temperture with --fod

---

src/hessian.F90

Fixed inverse sign of frequencies for unbiased SPH calculations

Sign error fixed for unbiased frequencies in SPH calculations

---

man/xcontrol.7.adoc
src/optimizer.f90
src/relaxation_engine.f90
src/set_module.f90
src/setparam.f90
src/type/setvar.f90

Will create an averaged convergence criteria for the optimization on non-smooth potential energy surfaces.
```
$opt
average conv=true
```

Implement an averaged convergence scheme for (L-)ANCopt

---

.github/workflows/fortran-build.yml
README.md

Notes for `xtb` on Windows:
- [cygwin](https://cygwin.com) POSIX environment can compile `xtb`.
- required packages: `gcc`, `gcc-fortran`, `libopenblas`, `lapack`, `meson`, `ninja`
- configure: `meson setup _build_gcc -Dla_backend=netlib`
- [MSYS2](https://msys2.org)
- msys POSIX environment does not work (`openblas`, `lapack` packages missing), use cygwin if you want a POSIX environment for `xtb`
- MinGW native compilation works
- required packages: `mingw-w64-*-gcc-fortran`, `mingw-w64-*-openblas`, `mingw-w64-*-lapack`, `mingw-w64-*-meson`, `mingw-w64-*-ninja`
- configure: `meson setup _build_gcc -Dla_backend=netlib`
Closes https://github.com/grimme-lab/xtb/pull/296

Add CI workflow for MinGW compiler toolchains

---

.github/workflows/fortran-build.yml
README.md

This PR adds a GitHub actions workflow for the Intel oneAPI classic compilers. The procedure to produce used in the workflow is similar enough to the setup I usually use to produce the release version, meaning the resulting version should be suitable to perform production calculations. Therefore, this PR also adds a continuous delivery of statically linked Intel binaries as cutting/bleeding edge version as well (use them with extra caution).
The workflow will run on every fork enabling GH actions and allows you to create Intel compiled releases on your development branches as well. For an example see: https://github.com/awvwgk/xtb/releases/tag/bleed

Intel oneAPI testing + continuous delivery

---

src/disp/dftd4.F90
src/intgrad.f90
src/xtb/CMakeLists.txt
src/xtb/dispersion.f90
src/xtb/meson.build
src/xtb/repulsion.F90

Adds OpenACC versions of repulsion and dispersion routines

Port repulsion and D4 dispersion with OpenACC

---

meson/meson.build
src/prog/main.F90

- print a warning on sequential builds if -P option is encountered
- pop argument of -P option from argparser to make command line consistent

Make commandline for threaded and sequential builds consistent

---

src/main/defaults.f90
src/prog/main.F90

- move default initialization of pcem input
Fixes https://github.com/grimme-lab/xtb/issues/374

Fix point charge embedding calculations

---

src/prog/argparser.f90

Fixes https://github.com/grimme-lab/xtb/issues/389

Fix detection logic of command line flags

---

CMakeLists.txt
meson.build

Finally, we are getting close to a new feature release (was about time). The release will be created shortly after this PR is merged.
*Release checklist*

Bump program version to 6.4.0

---

src/relaxation_engine.f90

This PR fixes #410.
I've tested that it works using [this xcontrol file for FIRE](https://github.com/grimme-lab/xtb/files/5908137/inertial_xcontrol.txt) and [this one for L-ANCOPT](https://github.com/grimme-lab/xtb/files/5908142/lbfgs_xcontrol.txt), with this [initial geometry](https://github.com/grimme-lab/xtb/files/5908147/h2o.txt).
Running L-ANCOPT prior to the fix yields this final geometry
3
xtb: 6.4.0 (d4b70c2b361067f291e81c3df1d1c31c28d01cb4)
H        -0.79575145519344    0.12524065205080   -0.00000000099274
H         0.96541707812111    0.14678380837277   -0.00000000237865
O         0.03033437297265    0.72797553581838    0.00000000000000
After this PR, running the same optimization yields
3
xtb: 6.4.0 (d4b70c2b361067f291e81c3df1d1c31c28d01cb4)
H        -0.77226423724448 …

Projection of fixed atoms out of Hessian in L-ANCOPT and FIRE optimizers

---

src/hessian.F90

External drivers are usually not thread-safe, account for this by not parallelizing the numerical differentiation.

Perform numerical differentiation for external drivers

---

.github/workflows/fortran-build.yml
src/extern/turbomole.f90

Was checking for `any` but should check for `all` coordinates

Fix caching logic in Turbomole calculator

---

src/prog/main.F90

- Warning currently almost always is a false positive flag

Remove warning for parallel runs

---

src/set_module.f90

Was documented as `grid` before but required `gbsagrid`, this patch allows both `grid` and `gbsagrid` in the detailed input.

Fix keyword name for gbsagrid

---

TESTSUITE/hessian.f90
src/freq/CMakeLists.txt
src/freq/meson.build
src/freq/numdiff.F90
src/hessian.F90

- Intel Fortran has problems to properly handle orphaned OpenMP
@ucb-mgcf, @sespic, @fabothch Do you mind rechecking your failing examples with the version uploaded at:
https://github.com/awvwgk/xtb/suites/2519893098/artifacts/54567679
Closes https://github.com/grimme-lab/xtb/issues/458

Fix parallelization strategy for numerical differention

---

TESTSUITE/gfn1.f90
src/intgrad.f90
src/peeq_module.f90
src/xtb/hamiltonian.f90

- slightly more consistent way to evaluate integrals
500 atom wall time reduces from 5.8s -> 5.4s (8 cores, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz).
4.7k atom memory usage reduced from 12G @ 10 cores to 1G @ 16 cores (see https://github.com/grimme-lab/xtb/issues/474).

Integral backend changes

---

src/gfnff/calculator.f90
src/gfnff/gfnff_setup.f90

Optional output of adjacency and coordination number for GFN-FF 
Signed-off-by: C.Hoelzer <hoelzer@thch.uni-bonn.de>

Writing adjacency to output

---

meson/meson.build
meson/openblas_lapack_test.f90

Add options used for `xtb` release builds. Warning: very expensive to compile (3x to 5x), decent speedup around ~2x with Intel Fortran.

Update meson build options

---

src/main/json.f90

Using the key `IR intensities` instead for `reduced masses`.

Fix duplicated key entry in JSON dump

---

src/main/property.F90

- add missing line break in case of zero neighbours
Closes #542 
Closes https://github.com/grimme-lab/xtb/issues/397

Fix formatting in bond order printout

---

man/xtb.1.adoc
src/oniom.f90
src/prog/main.F90
src/xhelp.f90

More convenient usage of `--oniom` with large inner region.

Allow specification of indices via file

---

man/xtb.1.adoc
src/printout.f90
src/xhelp.f90

- neither number of electrons nor spin available at this point
- cleanup some unused printout (removes one random_number call, among other things...)
Closes #575

Cleanup printout of spin

---

src/extern/orca.f90
src/prog/main.F90

- error on suspicious orca binary, like GNOME screen reader
- reduce printout from Orca with miniprint / nopop keywords
- add identifier to input file name to avoid restart from broken input

More robust Orca driver

---

src/type/molecule.f90

- periodic array provided by mctc-lib can be only one element (molecular case)

Ensure periodicity is set correctly

---

src/io/reader.f90

Required for crest. Thanks to @drmewes for reporting.

Fallback to coord input if format is unknown

---

src/gfnff/gfnff_setup.f90

- use success flag of restart reader to determine whether file was present

Don't check for existence of gfnff_topo

---

src/gfnff/gfnff_setup.f90
src/gfnff/struc_converter.f90
src/type/molecule.f90
src/xtb/repulsion.F90

- provide output unit for printing header in structure converter
- ensure fallback topology doesn't produce garbage for first atom
- recover bond topology from mctc-lib structure_type
Thanks to @hoelzerC for reporting.
Closes #603

Fix issues with structure converter

---

src/gfnff/gfnff_setup.f90

Handling of the .CHRG file in GFN-FF was broken, if no fragment charges were given. This should fix this.

Fix .CHRG handling in GFN-FF

---

src/extern/CMakeLists.txt
src/extern/driver.f90
src/extern/meson.build
src/extern/turbomole.f90
src/main/setup.f90
src/prog/main.F90
src/set_module.f90
src/setparam.f90

Simple reverse communication driver to run external scripts from `xtb`.
Needs some polishing.

Implement script driver

---

src/mctc/error.f90
src/mctc/mctc_init.F90
src/mctc/signal.c

Use iso_c_binding for building signal handlers

---

include/xtb.h
meson.build
test/api/c_api_example.c

Also add a convenience type generic macro for deleting API objects.
Not setting `c_std` can lead to failures with `icc` which default to a last century C standard (C89).

Bump C standard to C11 for using _Generic

---

test/api/c_api_example.c

MSVC cl has stricter rules about constants than other compilers
(e.g variables declared `const` are not constant at compile time and so
aren't consider constant). This means the compiler won't allow `const`
variables to be used to declare array sizes.
The changes here explicitly allocate/free memory for arrays so that
the MSVC cl compiler can run this example. The c-api itself should work
without these changes, but the example was incompatible and was halting
compilation.

Make c-api example MSVC compatible

---

src/api/calculator.f90
src/api/environment.f90
src/api/interface.f90
src/api/molecule.f90
src/api/results.f90
src/api/version.f90

* By default, the Visual Studio C compiler doesn't export any symbols,
so xtb.lib wasn't being created. Adding a def file of functions exported
and pointing to it in meson.build allows it create xtb.lib.
This should close https://github.com/grimme-lab/xtb/issues/646

Export API Symbols for MSVC

---

src/oniom.f90

The missing solvation contribution for the inner region calculations added

Add missing solvation contribution for the inner region

---

src/prog/CMakeLists.txt
src/prog/irmod.f90
src/prog/meson.build
src/prog/primary.f90
src/prog/submodules.f90

IR module is able to calculate IR spectra (frequencies and intensities) from DFTB+ output Hessian and Born charges. In case you want to do solid state TB calculations and obtain an approximate solid state IR spectrum.

Including IR module for DFTB+ output

---

src/setparam.f90

There was an error in the conversion of point charge coordinates in external embedding. The Orca flag was wrongly set to "true" without an "interface=orca" command. This led to deviations between point charge gradients calculated with the xTB binaries and our test suite. This will fix this. Will also close Issue #693 and PRs #718 and #719.

PCEM Conversion

---

CMakeLists.txt
cmake/modules/xtb-utils.cmake
test/unit/CMakeLists.txt

https://cmake.org/cmake/help/v3.9/command/make_directory.html
Signed-off-by: Eisuke Kawashima <e-kwsm@users.noreply.github.com>

replace deprecated `make_directory` with `file(MAKE_DIRECTORY)`

---

.github/workflows/fortran-build.yml

Seems like our continous delivery uses a deprecated command (https://go.dev/doc/go-get-install-deprecation). We should switch to go install instead.

Fix continous delivery.

---

src/prog/main.F90

The "--json" flag was not used with GFN-FF, which caused some confusion. In the future, we could use this flag to just write all available topology information in GFN-FF.
Related to #745.

Use --json flag in GFN-FF to write all topology information.

---

man/xtb.1.adoc

The xTB man page was not in accordance with our license. This will clarify this.

Clarifying xtb license

---

.github/workflows/fortran-build.yml
src/prog/main.F90
src/type/calculator.f90
src/type/molecule.f90
src/type/restart.F90

The new version of the ifort compiler in oneAPI 2023.0.0 seems to have problems with the copying of certain derived types. This compatibility patch introduces some additional copy routine which should hopefully fix this.
Also reverts the respective ifort github workflow back to the latest compilers as we can now build xTB with oneAPI 2023.0.0

Ifort 2023 compatibility

---

src/scf_module.F90

It seems like a fairly minimal amount of additional printing that can really clarify what written in the output.

Include SCC header with min printing

---

src/gfnff/gfnff_eg.f90
src/gfnff/topology.f90
src/main/json.f90
src/prog/main.F90

This was requested in issue #745

Add energy and gradient norm to wrtopo printout.

---

src/prog/main.F90

The ALPB solvation model is activated by setting the solvation environment variable ``alpb=True``. Because this is our default, up until now, we only deactivate the solvation model when someone uses the ``--gbsa`` flag. However, this leads to prioritizing a custom ``xtbrc`` file over the command line interface if someone explicitly states ``alpb=False`` in his configuration file.
This is counterintuitive. If the user requests ALPB via the command line interface, it should be explicitly activated.

Commandline flage "--alpb" now explicitly activates ALPB.

---

src/type/molecule.f90

One of our dependencies ([mctc-lib](https://github.com/grimme-lab/mctc-lib)) handles the logic of the allocation of PBC a little bit different than we did. This lead to errors with a specific version of the gfortran compiler when explicitly copying the molecular type, that was done as a compatibility fix for ifort in #752.
Handling the PBC logical explicitly for different sized logical arrays should fix this. This will close #772.

Fixes a bug that occurs when calculating an hessian specific builds

---

src/gfnff/gfnff_eg.f90
src/gfnff/gfnff_ini.f90
src/gfnff/topology.f90

This potential was requested to get the correct torsion potentials for diphenylacetylene.

Add torsion potential to GFN-FF for rotation around triple bonded carbon

---

meson/meson.build

When the meson options were renamed, the support for a custom lapack backend in meson.build was also removed. This patch restores that support.

Restore support for custom lapack backend

---

src/dynamic.f90

Ensure that metadynamics uses slightly different initial geometry

---

.github/workflows/fortran-build.yml

For some reason
parallelization doesn't function properly.

fix CI for MINGW64

---

.gitignore
src/gfnff/calculator.f90
src/gfnff/gfnff_eg.f90
src/oniom.f90
src/set_module.f90
src/setparam.f90
src/type/timer.f90

1) fix oniom `gfn2:gfnff` printout  for structure optimization by printing energies and gradients during each cycle
2) add `$ignore topo` instruction to bypass the topology check when cutting bonds
3) comment: `gfnff_eg.f90`, `timer.f90`, `oniom.f90`

Fix gfnff printout for oniom and add $ignore topo 

---

src/prog/main.F90
src/set_module.f90
src/setparam.f90

add set%clichrg pointer to distinguish if charge is entered via CLI.

add pointer for CLI charge initialization 

---

src/peeq_module.f90
src/scc_core.f90
src/scf_module.F90
test/unit/molstock.f90
test/unit/test_gfn2.f90

1) add Wiberg-Mayer bond orders for open-shell cases
2) add corresponding regression test (for GFN2)

open-shell WBOs

---

.github/workflows/fortran-build.yml

The xtb build with the most recent version of CMake (3.27.0) has some issues with the mctc-lib.
As a temporary solution, the older version 3.26.4 of CMake will be linked until the aforementioned issue is not resolved.

CMake temporary fix 

---

src/gfnff/gfnff_ini.f90
test/unit/test_gfnff.f90

Fixes GFN-FF bug for specific pi systems

---

src/filetools.F90
src/header.f90
src/local.f90
src/set_module.f90
src/type/iohandler.f90

The "basicatoms" list can be better parsed than the default printout and can be used in workflows, where basic reaction sides are important.

-lmo prints now list of basic atoms

---

src/prog/thermo.f90

It seems, the + sign in the "--dftb+" argument in the thermo submodule can lead to problems depending on the used environment.
I propose changing the default commandline argument to "--dftbplus", keeping "--dftb+" as an alternative for backward compatibility.
Closes #845.

Use "--dftbplus" instead of "--dftb+" in the thermo submodule.

---

src/oniom.f90
src/set_module.f90
src/setparam.f90
test/unit/test_oniom.f90

1) instruction to saturate outer region during ONIOM calculation.
``` fotran
$oniom
outer = bool
```

outer region saturation

---

src/extern/driver.f90
src/optimizer.f90

- write xtbopt.xyz constantly in the external driver mode so that not only "coord"-based external methods can be used for geometry optimization.
- nicer formatting

writing updated coord AND xtbopt.xyz during external driver optimization (including nicer printout)

---

man/xcontrol.7.adoc
src/oniom.f90
src/prog/main.F90
src/type/atomlist.f90

1) add warning if the distances between added link atom (H)  and any other atom is too short (smaller than H2) -> `check_dist`
2) update man page
3) allow for **0**  in TAtomList (e.g. `1,2,0,12`)

update ONIOM and TAtomList

---

src/solv/cpx.F90

CPCM-X expects the ``.cosmo`` file to be called "xtb.cosmo", independent of the namespace. This will fix this.

Fix namespace option with cpcmx

---

src/prog/main.F90
src/set_module.f90
src/setparam.f90

get rid of global SCC `accuracy` parameter

accuracy -> set%acc

---

src/prog/main.F90
src/scf_module.F90
src/set_module.f90
src/solv/CMakeLists.txt
src/solv/cosmo.f90
src/solv/ddvolume.f90
src/solv/input.F90
src/solv/meson.build
src/solv/model.f90
src/xhelp.f90

Related to #863. Uses the TM convention for the writing of ``.cosmo`` files in xTB when the "--tmcosmo" keyword is used.
Edit: Given the scope of this PR, this will now completely close #863 if merged.

Add "--tmcosmo" mode for writing .cosmo files with TM convention.

---

src/docking/param.f90
src/docking/set_module.f90
src/prog/dock.f90

The additional attractive/repulsive potential for the directed docking feature of the `aISS` algorithm can now be scaled.
Therefore, the `scaling factor= <value>` keyword of the `$directed` block in the additional input file is used.

Introducing a scaling factor for directed docking

---

src/oniom.f90

`real(wp)` was missing; instead only a simple `real` was used.

accuracy parameter in variable declaration missing

---

src/scf_module.F90

add `embd` the `scc_results%e_elec` term, so the total energy can be calculated as the sum of the printed terms.

add embd term to scc energy

---

src/disp/dftd4.F90
src/oniom.f90
src/type/molecule.f90

CMake build in debug mode results in several runtime errors (with both `gfortran` v11.4.0 and `ifort` v2021.5.0):
1. Race condition in `dftd4.f90`
2. Out of bound exception in `oniom.f90` 
3. Dimension mismatch in `molecule.f90`

resolve debug compilation errors

---

src/extern/driver.f90
src/extern/orca.f90
src/main/setup.f90
src/prog/main.F90
src/setparam.f90

update all ORCA-related code:
1. enhance the readability of `orca.f90` and `driver.f90 `
2. add `checkExe` to validate the external binary 
3. add `chkInput` and `firstArgComesFirst` to check for ORCA input for certain keywords and their order
4. rewrite `writeOrcaInp` 
5. add an extra level of error handling (`exitstat` does not catch **OpenMPI**-related ORCA crashes )

refactor ORCA calculator

---

man/xcontrol.7.adoc
man/xtb.1.adoc
src/prog/main.F90
src/set_module.f90

Ensure consistency between xcontrol instructions and command-line arguments for SCC control options.

consistent SCC options

---

.github/workflows/fortran-build.yml
README.md

Address the issue of the new ifort version not compiling programs by temporarily reverting CI to an older version of ifort as a workaround, until ifx is fully integrated.

temporary fix for CI

---

.github/workflows/fortran-build.yml
CMakeLists.txt
meson.build

For the **CMake** build:
1. Enable the building of an object library for CMake versions newer than 3.28.0.
2. Allow compilation with preprocessor definitions.
For the **Meson** build:
1.  Enable preprocessor definitions in the main.f90 .

fix preprocessor definitions

---

src/geoopt_driver.f90
src/optimizer.f90
src/prog/main.F90

1.  Implement partial optimization of the `xtbMain` subroutine.
2.  Add detailed comments to the `xtb_geoopt` module to enhance code clarity
3.  Introduce the **tsopt.f90** file for the forthcoming Transition State (TS) optimizer.

refactor geometry optimization (part 1)

---

CMakeLists.txt

I was trying to compile xtb and it was failing with
```
Error: macro names must be identifiers
```
I traced it back to this line where an extra -D was being applied to these flags. Maybe this works as is with a different version of cmake? Happy to close this PR if everything is working as intended. But it compiled successfully for me after applying this patch.
cmake=3.22.1
gfortran=11.4.0
gcc=11.4.0
ubuntu=22.04

Fix build error "macro names must be identifiers"

---

man/xtb.1.adoc
src/main/property.F90
src/prog/main.F90
src/set_module.f90
src/setparam.f90
src/xhelp.f90

add `ptbsetup` variables `raman_temp` and `raman_lambda`

raman activities with adjustable wavelength and T

---

src/hessian.F90

set higher SCC accuracy for the numerical hessian calculations (variable `set%accu_hess` has already been defined, but not used).

use accu_hess

---

.github/workflows/stale_label.yml

Automatically close PRs and issues labeled as **stale** if there's no activity within 7 days.

add Stale workflow

---

meson/meson.build
src/gfnff/gfnff_eg.f90
src/gfnff/gfnff_ini.f90
src/gfnff/gfnff_ini2.f90
src/gfnff/topology.f90
src/restart.f90

The matrix considered_ABH(n,n,n) allocation used in the HB scaled bond energy was unnecessarily large. I introduced a mapping from the atom index to the hb index for AB atoms and H atoms separately. Since this is done in the initialization of the force field, the new variables need to be part of the topology as well.

Reduce memory usage in egbond_hb for GFN-FF

---

test/unit/meson.build

include  the preprocessor flags during regression tests in the Meson build.

include preprocessor definitions 

---

src/ptb/calculator.F90
src/tblite/CMakeLists.txt
src/tblite/calculator.F90
src/tblite/mapping.F90
src/tblite/meson.build
src/type/data.f90
src/type/wavefunction.f90

add **src/tblite/mapping.f90** to convert tblite wfn and SCC results into the internal xtb data types.
Any suggestions on how to improve this would be highly appreciated, as this is step toward fully integrating tblite into xtb and potentially using it as the main driver for xtb methods in the future.

mapping between tblite and xtb

---

src/axis_trafo.f90
src/detrotra.f90
src/main/property.F90
src/optimizer.f90
src/qsort.f90
src/setparam.f90
src/type/anc.f90
src/type/setvar.f90
test/unit/test_thermo.f90

Refactoring of ANCopt-related procedures.
The modifications have been segmented into multiple commits for easier tracking of the changes

refactor geometry optimization (part 2) 

---

src/thermo.f90

Applies the fix suggested in #593 which should help with #1052. This should allow Dinfh and Cinfh symmetries.

Increase number of characters for Schoenflies notation from 4 to 6

---

src/dipro.F90
src/dipro/xtb.F90
src/tblite/calculator.F90
subprojects/mstore.wrap
test/unit/test_ptb.F90

- receive `error_type` from `tblite`'s `new_*_calculator` call
- more recent `mstore`  version for _f_-block compounds
- adapt PTB tests to changed ordering of _d_ orbitals in `tblite`

Make xtb compilable with latest tblite commit (6b7ee4e) EDIT: (6426ee4)

---

meson/meson.build

* Use `fc_id` throughout meson.build, rather than repeatedly calling `fc.get_id()`. 
* Wherever we previously branched for `"intel"` (ifort compiler), also branch for `"intel-llvm"` (ifx compiler).

Detect ifx (intel-llvm) when determining compiler settings

---

src/gfnff/gfnff_eg.f90

I had the same compilation error as reference in #1012 , #998,  and #997.
This is clearly some sort of bug in gcc as it is clearly passing an array to product.
Unless I am misunderstanding something, changing to hardcoded numbers should not pose a problem. If desired, I could also do the explicit product. e.g. `(2*ewaldCutD(1) + 1)*(2*ewaldCutD(2) + 1)*(2*ewaldCutD(3) + 1)`
Closes #1012
Closes #998
Closes #997

change product to hardcoded number fixes #1012 fixes #998 fixes #997

---

subprojects/dftd4.wrap

Take more recent `dftd4` version to prevent tests from failing.
```
[wrap-git]
directory = dftd4
url = https://github.com/dftd4/dftd4
revision = v3.6.0
```

Fix dftd4 tests by updating to more recent version

---

meson/meson.build
meson_options.txt

In this [recent commit](https://github.com/grimme-lab/xtb/commit/fe552967cefb806d68d7619f0324e9fdd424573e) DFTD4 and multicharge were added as dependencies for xTB. As far as I can tell, these dependencies aren't currently used (all unittests pass without them, as well as a variety of individual calculations that I have tried).
If the intention is to eventually have DFTD4 and multicharge be required dependencies, this isn't toggling isn't strictly needed, but is nice to have in the interim until features that use that use these  dependencies are added. 
My motivation for making the pull request was that I hit a build failure on Windows (ifort/msvc compilers) trying to compile the multicharge dependency:
```
[stdout] [238/690] Compiling Fortran object …
```

Make DFTD4 & multicharge dependencies optional

---

.github/workflows/fortran-build.yml
yamlfmt.yml

- update `gfortran` and `meson` versions
**NOTE:** The failing `CI / gcc-meson-build (macos-latest, 11)` is due to a failure in the subproject https://github.com/grimme-lab/CPCM-X, detailed [here](https://github.com/grimme-lab/CPCM-X/issues/38).

Update GitHub workflow to latest state

---

.github/workflows/fortran-build.yml

- remove `gcc-11`
Based on the following announcement:
https://github.com/actions/runner-images/issues/10213

Remove `gcc-11` from CI on macOS as it got removed from the images

---

include/xtb.h
src/api/calculator.f90
src/api/interface.f90
src/api/results.f90
src/api/version.f90
src/scf_module.F90
test/api/c_api_example.c
test/api/meson.build

Addresses https://github.com/grimme-lab/xtb/issues/1065 (and partially https://github.com/grimme-lab/xtb/issues/336) 
This adds a parameter to `setSolvent_api` to allow it to also set the solvent model used. Depending on concerns about API stability, I could make a new `setSolventWithModel_api`.
In addition, a convenience method is added for running CPCM-X calculations. This handles running both the SCF loops.
New API tests were added for the ALPB, COSMO, and CPCM-X solvent models.
Results object now stores a solvation energy, accessible through `xtb_getSolvationEnergy`.

Add option to select solvent model to the C-API

---

README.md

- hint towards `gcc`, `gfortran`, and `openblas`
- setup of relevant environment variables

Update README.md with hints for macOS

---

src/gfnff/gfnff_ini.f90
src/set_module.f90
src/setparam.f90

The array used for the adjustment of the GFN-FF neighbor list (set%ffnb) is now allocated dynamically.
The first dimension is always the maximum number of neighbors allowed in GFN-FF (42 since 6.7.1) and the second dimension is the number of atoms that the neighbor list should be adjusted for.

Allocate set%ffnb dynamically.

---

README.md
src/xtb/hamiltonian.f90

This patch removes uninitialised but used stmp that leads to bugs with novel GCC's. All cmake tests for xtb were passed. 
Fixes #1109

Fix for GCC 14

---

src/constrain_pot.f90

This patch fixes Internal Compiler Error (ICE) of ifx 2024.1.0.
Discussion about this ICE is available here: https://community.intel.com/t5/Intel-Fortran-Compiler/xtb-ICE-during-compilation-of-constrain-pot-f90/m-p/1632218/highlight/true#M173722
Shortly, during compilation one can obtain the following message:
```
#0 0x00000000023916e2
#1 0x00000000023f5bc7
#2 0x00000000023f5cf0
#3 0x00007f232544fb50
#4 0x0000000004394b15
#5 0x0000000004395724
#6 0x0000000004394bd1
#7 0x0000000004391eec
#8 0x000000000439099c
#9 0x000000000438ffe2
#10 0x000000000339c5af
#11 0x000000000339c42d
#12 0x000000000272fcd5
#13 0x00000000023452ed
#14 0x0000000002736dbd
#15 0x000000000234505d
#16 0x000000000272ea2a
#17 0x000000000232eacf
#18 0x000000000232cf52
#19 0x00000000022d97eb
#20 0x00000000024b171c
#21 …
```

Fix ICE for ifx 2024.1.0

---

src/optimizer.f90

This patch fixes optimization issues comes from refactoring of geometry optimization done in #982.
I optimized some medium-size systems (~500-1500 atoms) and noticed that results between versions 6.7.0 and 6.7.1 are different. Moreover, geometry optimizations started to fail in 6.7.1 version, while it was OK for 6.7.0 version.
I found that problem comes from commit https://github.com/grimme-lab/xtb/pull/982/commits/5366177e23b0ad7f5b09ea6d1759c38dd11c4609, in which the blowing up of hessian was moved.
I have tested this patch with a few iterations of my systems and it works almost like with 6.7.0 version.
Closes #1073

Fix optimization issues after #982

---

src/optimizer.f90

In rare cases when davidson fails, solver_sspevx was called. Unfortunately, it did not update fail variable, so, if it even was successful, fail variable still was true and therefore optimization was failing.
This patch fixes this issue.

Fix optimization when davidson fails

---

src/constrain_pot.f90
src/gfnff/frag_hess.f90
src/gfnff/gfnff_eg.f90

Closes #1136
Closes #1137
Closes #1138
I have reordered cycles in constrain_pot.f90 and optimize them a little bit.
In frag_hess.f90 the interfaces were written improperly. With this patch, it is fixed.

Fix some warnings

---

src/local.f90

By some reason, at https://github.com/grimme-lab/xtb/blob/c3cfd38d6753f92a07a916a47a52114af9e6b989/src/local.f90#L278 `xtbscreen.xyz` was opened at first scope level, but the file was closed at second scope level, and therefore, if the following check was failed:
https://github.com/grimme-lab/xtb/blob/c3cfd38d6753f92a07a916a47a52114af9e6b989/src/local.f90#L360
the close statement does not work for `xtbscreen.xyz` and then, at the next iteration, this file was opened at the second time.

Fix multiple open of xtbscreen.xyz in local.f90 (xtb/iff test)

---

.github/workflows/fortran-build.yml

Broken tests with CMake + Debug, so these build are currently disabled:
on x86_64:
```
The following tests FAILED:
57 - tblite/gfn1-xtb (NUMERICAL)
88 - xtb/docking (NUMERICAL)
90 - xtb/gfn0 (NUMERICAL)
91 - xtb/gfn1 (NUMERICAL)
94 - xtb/hessian (Failed)
95 - xtb/iff (NUMERICAL)
101 - xtb/peeq (Failed)
106 - xtb/vertical (Failed)
116 - xtb/GFN0-xTB (NUMERICAL)
```
on Aarch64:
```
The following tests FAILED:
88 - xtb/docking (Failed)
93 - xtb/gfnff (Failed)
94 - xtb/hessian (Failed)
106 - xtb/vertical (Failed)
107 - xtb/wsc (Failed)
```

Fix ubuntu-latest CI and introduce Arm validation

---

src/optimizer.f90
src/prog/main.F90
src/set_module.f90
src/setparam.f90
src/tblite/calculator.F90

The implementation of the numerical charge gradients `num_grad_chrg` (for CEH).
The output is written to **ceh.grad**.
@lukaswittmann, please be careful with the [output](https://github.com/grimme-lab/xtb/blob/1186b5a4b3338a78e6ebe4e95d7dec924c536e90/src/tblite/calculator.F90#L495-L497) format.

CEH gradients

---

src/constrain_param.f90

before, only single entries like:
```
$hess
modify mass: 12, 2.0, 3, 4.0
scale mass: 2, 1.5, 5, 6.0
$end
```
were possible.
Hyphen-separated ranges of atoms can be read in, like:
```
$hess
scale mass: 12-50,2.0
modify mass: 1-3,400.0
$end
```

Enable hyphen separated range of atoms to modify mass

---

src/axis_trafo.f90
src/basic_geo.f90
src/constr.f90
src/drsp.f
src/elem.f90
src/esp.f
src/geosum.f90
src/intpack.f90
src/lindh.f90
src/local.f90
src/lopt.f90
src/makel.f90
src/model_hessian.f90
src/prmat.f90
src/rdcoord2.f90
src/readl.f90
src/rmsd.f90

This PR defines all unknown types to integer where it was necessary. Now, code can be compiled with `gfortran -fimplicit-none`.

Define types of all variables 

---

src/docking/search_nci.f90

The `fast mode` printed in the output does not refer to the `--fast` flag, but to the use of the ATM term. This was clarified with the commit.

Clarified the aISS output

---

src/main/geometry.f90

Integer `(kind=4)` overflow may be easily achieved at line:
https://github.com/grimme-lab/xtb/blob/7b9935b95138893db86045ac74864883b3424e9b/src/main/geometry.f90#L153
To avoid this,  variables `maxdist`, `maxbend`, and `maxtrsn` have integer `(kind=8)` type now.

Avoid integer overflow in main/geometry.f90

---

src/prog/main.F90

- Isotope masses were overridden by physical values.
- shift initialization of atomic masses directly to line directly after allocation of the array `atmass` (see `init_split`).

Fix isotope hessian

---

src/hessian.F90

- line containing the info about the printed `hessian` file is extended.
- Closes https://github.com/grimme-lab/xtb/issues/611

Clarify units of the Hessian matrix

---

src/main/geometry.f90

Probably affects #621
Before patch, one distance were skipped between atoms `# N` and `# N-1`. For single-bonded systems (like H2) it is critical since it means that they were not bounded and then a lot of artefacts happen. 
Fixes #850. Changes in output:
```diff
* 1 selected distances
-     0   0      0   0                                     0.0000000 (max)
+     1   1 H        2   1 H                                       0.7769870 (max)
- * 0 distinct bonds (by element types)
+ * 1 distinct bonds (by element types)
Z      Z             #   av. dist./Å        max./Å        min./Å
+   1 H    1 H           1     0.7769870     0.7769870     0.7769870
```

Fix exit condition in calc_distances

---

src/iff/iff_prepare.f90
src/local.f90
src/scf_module.F90

I have initialized some variables with zeros.
- `er` for later `call goedecker_chrgeq` where `er` is `inout`,
- `sigma` for later `call repulsionEnGrad` where `sigma` is `inout`,
- `dum` for later `call d4_gradient` where `energy=dum` is `inout`,
- arrays in local.f90 mostly for `ecent` by similar reasons

Initialize some variables for xtb/iff test

---

src/disp/dftd3.f90
src/disp/dftd4.F90

Instead of having `Inf` in `norm` after dividing by itself (when equals 0.0), now `norm` equals 0.0 and therefore `gwk` will equal 0.0 as well as `dgwk`.

Avoid division by zero in disp module

---

src/hessian.F90

Fixes #475 
This patch updates hessian.F90 to properly work with freezed atoms (and a little bit with fixed, but I did not get the difference between fix and freeze). With this patch, input (provided in #475) can be computed without segfaults (fixed in commit [53aaa53](https://github.com/grimme-lab/xtb/commit/53aaa53ed4f301fb54ea8a93284f8a70c9c4db8d)) and produced Hessian has zero values for fixed atoms and fixed-free atom crossings, so it looks fine for me :-)
Unfortunately, I did not implement all branches and therefore hessian with 1-2 fixed atoms can not be computed.

Fix hessian with fixed atoms

---

src/docking/search_nci.f90
src/iff/iff_energy.f90
src/iff/iff_ini.f90

During careful running of xtb/docking test via CMake I have found several divisions by zero and improperly closing of files. This patch resolves such issues

Fix xtb/docking test

---

src/relaxation_engine.f90

This patch fixes some incorrect allocations to their proper size for using `anc` and `hdiag` variables in array statements like:
here for hdiag:
https://github.com/grimme-lab/xtb/blob/c3cfd38d6753f92a07a916a47a52114af9e6b989/src/relaxation_engine.f90#L849
(`d` and `q` have size `nvar`, while `hdiag` had size `nat3`)
here for anc:
https://github.com/grimme-lab/xtb/blob/c3cfd38d6753f92a07a916a47a52114af9e6b989/src/relaxation_engine.f90#L1053
(`displacement` has size `nvar`, while `anc` had size `nat3`)

Fix L-BFGS memory accesses

---

src/docking/search_nci.f90

Fixed a bug that caused crashes during the aISS procedure when distances, angles, or dihedral angles were constrained.

Fixing aISS distance constrain fix

---

src/generate_wsc.f90

This PR removed data-races from shared minpos/mindist/nminloc/nmindist. Now, `wsc` and `peeq` tests should be repeatable.

Update OpenMP parallelization in WSC to avoid data-races

---

src/docking/search_nci.f90

Fixes `xtb/docking` test of CMake debug Aarch64 build. 
Stacktrace:
```
Starting stack search
Grid points: 14000
At line 603 of file /home/runner/work/xtb/xtb/src/docking/search_nci.f90
Fortran runtime error: Index '0' of dimension 1 of array 'mvec' below lower bound of 1
Error termination. Backtrace:
#0  0xff6faad0d44b in ???
#1  0xff6faad0e277 in ???
#2  0xff6faad0e7cb in ???
#3  0xab162411c01f in __xtb_docking_search_nci_MOD_docking_search
at /home/runner/work/xtb/xtb/src/docking/search_nci.f90:603
#4  0xab1623f31467 in test_dock_eth_wat_gfn2
at /home/runner/work/xtb/xtb/test/unit/test_docking.f90:180
#5  0xab1623ec9d4f in run_unittest
at /home/runner/work/xtb/xtb/test/unit/main.f90:169
#6  0xab1623eca1e7 in run_testsuite
at /home/runner/work/xtb/xtb/test/unit/main.f90:149
#7 …
```

Avoid 0-indexed access in search_nci.f90

---

src/peeq_module.f90

This PR fixes `xtb/gfn0` and `xtb/GFN0-xTB` tests which fails with the following stacktrace:
```
Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.
Backtrace for this error:
#0  0x7f866aa23e59 in ???
#1  0x7f866aa22e75 in ???
#2  0x7f866804532f in ???
#3  0x5580b9190c2b in __xtb_pbc_MOD_get_realspace_cutoff
at /home/runner/work/xtb/xtb/src/pbc.f90:62
#4  0x5580b919ea51 in drep_grad
at /home/runner/work/xtb/xtb/src/peeq_module.f90:675
#5  0x5580b91aad0a in __xtb_peeq_MOD_peeq
at /home/runner/work/xtb/xtb/src/peeq_module.f90:528
#6  0x5580b8f7ed56 in __xtb_xtb_calculator_MOD_singlepoint
at /home/runner/work/xtb/xtb/src/xtb/calculator.f90:269
#7  0x5580b8ab8811 in __xtb_prog_main_MOD_xtbmain
at /home/runner/work/xtb/xtb/src/prog/main.F90:698
#8 …
```

Avoid division by zero in `xtb/gfn0` and `xtb/GFN0-xTB` tests

---

src/solv/model.f90

Adds additional solvent aliases for various supported solvents.
`normalizeSolventName` now chooses a consistent name to use for a given solvent internally.
Addresses https://github.com/grimme-lab/xtb/issues/1147

Solvent aliases

---

.github/workflows/fortran-build.yml
test/unit/test_hessian.f90
test/unit/test_vertical.f90

All tests in Debug mode are passed now. Hope, in future they also will be passed.
`tblite/gfn1-xtb` was disabled. See https://github.com/tblite/tblite/issues/227

Enable CMake Debug builds

---

src/gfnff/gfnff_eg.f90

This patch fixes flicking gfnff test that sometimes happens on MacOS runners due to out-of-memory access. 
As I can see, there should be an additional term related to topology constraints, however, it was never implemented for gradients.

Fix flicking xtb/gfnff test

---

src/scf_module.F90
test/unit/test_gfn2.f90

Fix #986 
If one of coordinates close to another in another atom, S(ii,jj) tends to zero, at the same time corresponding H0 is also tends to zero and therefore H0(k)/S(ii,jj) is constant. But since S(ii,jj) was skipped, the H(ii,jj) becomes zero that is incorrect.

Fix gradient evaluation when one of coordinates is close to another

---

.github/workflows/fortran-build.yml
src/type/calculator.f90

Closes #908 
It is not clear how does it work outside of test suite.

Introduce ifx

---

src/io/reader/genformat.f90
src/io/reader/orca.f90
src/io/reader/turbomole.f90
src/mctc/resize.f90
src/mctc/symbols.f90
src/type/identitymap.f90
src/type/molecule.f90
test/unit/test_gfnff.f90
test/unit/test_hessian.f90
test/unit/test_vertical.f90

Alternative approach to #1172 
This PR removes symbolLength variable from xtb_mctc_symbols module and changes behaviour to use dynamically sized strings.
Fixed the following error for CMake debug build on Aarch64 (as well as #1172):
```
At line 243 of file /home/runner/work/xtb/xtb/src/mctc/symbols.f90
Fortran runtime error: Actual string length does not match the declared one for dummy argument 'symbol' (1/4)
Error termination. Backtrace:
#0  0xff0d6362d44b in ???
#1  0xff0d6362e277 in ???
#2  0xff0d6362e7cb in ???
#3  0xab6d17e20527 in __xtb_mctc_symbols_MOD_getidentitysymbol
at /home/runner/work/xtb/xtb/src/mctc/symbols.f90:243
#4  0xab6d17fb8c17 in __xtb_type_molecule_MOD_initmolecule
at /home/runner/work/xtb/xtb/src/type/molecule.f90:263
#5  0xab6d17fb5bf7 in …
```

Remove symbol length variable

---

src/local.f90
src/main/property.F90
src/peeq_module.f90
src/scc_core.f90

Fix for the NaN value of the Fermi-level if there are no electrons in either alpha or beta (or both) channels. Now, the Fermi-level is set to the lowest available eigenvalue. This leads to a consistent Fermi-level for radicals, where the alpha and beta levels are averaged. Additionally, I combined all checks for the applicability of Fermi smearing (i.e. whether the species has virtual orbitals) in the same place. I checked that FOD remains unchanged. This should address #1169. 
Closely related to this, I skipped the MO localization with the `--lmo` flag if there is no electron present. This leaves the output unchanged (i.e. the analysis and output files remain the same) but avoids MKL issues during the matrix multiplication if the number of occupied orbitals is zero. I added a warning if …

Fix NaN Fermi-level 

---

src/gfnff/calculator.f90
src/xtb/calculator.f90

This fixed #1185 by now explicitly stating that the second energy is also without Gshift. Due to the formatting the total energy part has to be removed. Does anyone have better ideas how to possibly handle that?

Solvation printout, fix for #1185

---

src/gfnff/gfnff_ini.f90

Pass the array with user provided neighbors to be used for setting up EEQ constraints.
Resolves #1216

Use user provided nb for EEQ constraint

---

src/prog/main.F90
src/vertical.f90

- The previous spin state assignment set the wavefunction to be open-shell for the anionic case if the original wavefunction has already been open-shell (see the relevant line of code below). If I don't have a major logic issue this seems to have been wrong in general before (`wf_an` is only a copy from the ground-state wavefunction calculated before), and the other way round would be correct (in the simplest case: a neutral closed-shell molecule becomes open-shell in the ionized case). The spin state assignment has been changed to a more reasonable logic.
```Fortran
if (mod(wf_an%wfn%nel,2).ne.0) wf_an%wfn%nopen = 1
```
- Since PTB does not allow for restarting a calculation, assigning the spin state only in the wavefunction does not have any effect. Before, the Fukui calculation crashed …

Fix Fukui function for PTB and change spin-state assignment

---

src/relaxation_engine.f90

At 
https://github.com/grimme-lab/xtb/blob/41059b44d84a07dfd99a051e4409ef654faca939/src/relaxation_engine.f90#L1418-L1419
the reading of uninitialized variable may generate SIGFPE. This patch defines `lat_gnorm` as well as other variables related to optimization of cells to avoid such behaviour.

Init some variables in relaxation engine

---

src/solv/cosmo.f90
src/solv/gbsa.f90

This parameter are not used anywhere in code and therefore can be easily removed.

Remove unused gammas

---

src/main/property.F90

- prevent "stars" (numbers too large for `f6.2`) in the vibrational spectroscopy intensity output
- closes #1174

fix IR/Raman intensity output

---

src/freq/io.f90
src/hessian.F90

- fix the calculation of the reduced mass to consistent with reference calculations in other implementations as well as DFT reference data (see issue #367)
- more consistent variable names to avoid exploiting variables for different purposes (`isqm` serves also as scratch variable in a later part of the code)
- closes #367
- took Psi4 implementation https://github.com/psi4/psi4/blob/0df59280773a86f7ae1f6cc577731074a0fbaad9/psi4/driver/qcdb/vib.py#L582 as reference and documentation from: https://gaussian.com/vib/
**Normalization** is a relatively straightforward process. Before it is printed out, each of the `3N` elements of `l_{\text{CART},k,i}` is scaled by the normalization factor `N_i` for that particular vibrational mode. The normalization is defined by:
$$
N_i = \sqrt{ \left( \sum_k …

Fix reduced mass calculation

---

.github/workflows/fortran-build.yml

Couple days ago, Intel released 2025.1 compiler. Hope, they fixed bugs which were in previous release. 
This PR adds latest version into CI to validate that xtb & compiler compiles and works correctly.

Add Intel LLVM 2025.1 compiler

---

src/anharmlib.f90
src/broyden.f90
src/constr.f90
src/eqrot.f90
src/fragment.f90
src/geosum.f90
src/getname.f90
src/ifind.f90
src/intmodes.f90
src/lindh.f90
src/locmode.f90
src/matinv.f90
src/neighbor.f90
src/onetri.f90
src/oniom.f90
src/pocketscan.f90
src/printmold.f90
src/prmat.f90
src/rabguess.f90
src/rmrottr.f90
src/rmsd.f90
src/shiftlp.f90
src/vertical.f90
src/wrmodef.f90
src/zmatpr.f90

By some reason (most probably F77->F90 conversion), all lines were cut to 72 symbols, while some strings had more than 72 symbols. This patch fixes those lines.

Licen -> License

---

src/coulomb/klopmanohno.f90
src/disp/dftd4.F90
src/xtb/hamiltonian.f90

This PR improves parallelization for GFN2 geometry optimization. It affects other types of calculations too.
Achieved speed-up is **30%**. Gradients are **2x** faster!
For 578 atom structure, before the patch:
```
total:
* wall-time:     0 d,  0 h,  1 min, 11.680 sec
*  cpu-time:     0 d,  0 h,  3 min,  7.524 sec
* ratio c/w:     2.616 speedup
SCF:
* wall-time:     0 d,  0 h,  0 min, 13.534 sec
*  cpu-time:     0 d,  0 h,  0 min, 41.212 sec
* ratio c/w:     3.045 speedup
ANC optimizer:
* wall-time:     0 d,  0 h,  0 min, 57.390 sec
*  cpu-time:     0 d,  0 h,  2 min, 25.103 sec
* ratio c/w:     2.528 speedup
normal termination of xtb
real 1m11.740s
user 3m5.985s
sys 0m1.572s
```
After the patch:
```
total:
* wall-time:     0 d,  0 h,  0 min, 48.779 sec
*  cpu-time:     0 d,  0 h,  2 min, …
```

Speed-up hot path of GFN2 geometry optimization 

---

src/main/json.F90

Initialize default variable for avoiding extra comma in json

---

src/disp/dftd4.F90
src/scc_core.f90

This PR introduces a small set of OpenMP optimizations which slightly speeds up each geometry optimization step.
Tested with ifx 2025.1.
See commit messages about impact of each of optimizations.

Speed-up gradient evaluation

---

src/gfnff/gfnff_ini.f90

For systems with large partial charges (such as mindless molecules), the charge factor `qafac` for the bond parameter `neigh%vbond(3,:)` can become a large negative number. This results in the exp() to get infinite at https://github.com/grimme-lab/xtb/blob/7fc982ac70f5b1d37479f4fc33913fb1e9500aac/src/gfnff/gfnff_ini.f90#L1318 and https://github.com/grimme-lab/xtb/blob/7fc982ac70f5b1d37479f4fc33913fb1e9500aac/src/gfnff/gfnff_ini.f90#L1342 which was not properly handled.
I implemented an if condition that assigns the asymptotic limit for large exponents.

Fix ebond charge scaling for large negative factors qafac

---

src/prog/main.F90

Fixes #1285 
subroutine `set_gfn` just checks that `ff` was passed and exit immediately. No actual setup was happened.

Allow run GFN-FF with `--gfn ff`

---

src/coulomb/ewald.f90
src/coulomb/gaussian.f90
src/coulomb/klopmanohno.f90
src/disp/coordinationnumber.f90
src/disp/dftd3.f90
src/disp/dftd4.F90
src/freq/project.f90
src/gfnff/gdisp0.f90
src/gfnff/gfnff_eg.f90
src/peeq_module.f90
src/solv/gbsa.f90
src/type/coulomb.f90
src/xtb/hamiltonian.f90
src/xtb/repulsion.F90

With gfortran, spread intrinsic is not optimized (more precisely this is libgfortran call) and therefore it significantly affects on performance, especially for 3-body terms. 
This patch speeds up gradient code in 1.5-2x times with gfortran as well other parts which I did not measure. By some reason, it also affects ifx but it gives only 10% speed up for `deriv_atm_triple` subroutine. 
I have used unrolled cycles since they provide an extra optimizations for ifx: time was improved from 680 to 625 ms for my input. Usual cycles does not give this improvement: see the assembler difference here: https://godbolt.org/z/zs6e7vzT4. The first source code is the original, the second is presented in this PR and the third one uses cycles. 
I did not touched initializations/io parts where spread are …

Avoid spread intrinsic

---

src/disp/dftd4.F90

This patch speeds up `deriv_atm_triple` from 360 CPU cycles to 160 CPU cycles on x86-64-v3 Arch with GCC 14.2. This routine takes about half of time for gradient evaluation for medium size molecules. Intel compiler is also affected with close impact.

Update `deriv_atm_triple` subroutine

---

src/prog/main.F90

If the electronic temperature was specified via the --etemp command line flagcommand, its value did not change when using --tblite.

electronic temperature now also set for tblite correctly via command line flag --etemp

---

src/prog/main.F90

Previously, the thermodynamic properties were not written to the JSON output due to the incorrect order of operations.

Write output JSON after frequency analysis
